{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-wasmtime-android/0.3.0-dev.428bfc8e397e/runtime-wasmtime-android-0.3.0-dev.428bfc8e397e.module",
    "group": "uk.shusek.krwa",
    "module": "runtime-wasmtime-android",
    "version": "0.3.0-dev.428bfc8e397e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-wasmtime-android.aar",
          "url": "runtime-wasmtime-android-android-0.3.0-dev.428bfc8e397e.aar",
          "size": 26925862,
          "sha512": "24749a1e5d67b3e37745e8e5607788395803082770752d4e497d74b46f36c36ef577359b8fad02b3de0ff0228dbc004713b88b65bb0bd4c6291dee7b7912aa5c",
          "sha256": "ec9887ad7e95687191dc12448861a2f8c31287c69aeeb1b7dd4447bfa57f0a04",
          "sha1": "195b106f65dd1429d8598e6131eeafaa92bbf64a",
          "md5": "bf543cc8db85d578bb233d649711d3c0"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-wasmtime-android.aar",
          "url": "runtime-wasmtime-android-android-0.3.0-dev.428bfc8e397e.aar",
          "size": 26925862,
          "sha512": "24749a1e5d67b3e37745e8e5607788395803082770752d4e497d74b46f36c36ef577359b8fad02b3de0ff0228dbc004713b88b65bb0bd4c6291dee7b7912aa5c",
          "sha256": "ec9887ad7e95687191dc12448861a2f8c31287c69aeeb1b7dd4447bfa57f0a04",
          "sha1": "195b106f65dd1429d8598e6131eeafaa92bbf64a",
          "md5": "bf543cc8db85d578bb233d649711d3c0"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "runtime-wasmtime-android-android-0.3.0-dev.428bfc8e397e-sources.jar",
          "url": "runtime-wasmtime-android-android-0.3.0-dev.428bfc8e397e-sources.jar",
          "size": 12270,
          "sha512": "21cde2a5ab70ab127bbb695f20d7a12c33da1840e687236648b7219eefd898be141ed90272566652dbf92e3dcc0c8c0a198e012aa0453d33d387455cb2295491",
          "sha256": "e2a575353f96cdda21765b200180dd14fda1da12423f95d60ff5fd5dc4f48f6e",
          "sha1": "87ae593063d1351087b93dff28665545e79b40a9",
          "md5": "cf62c7306307acc795380b40d69bc309"
        }
      ]
    }
  ]
}
