{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "wabt",
    "version": "0.3.0-dev.428bfc8e397e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wabt-0.3.0-dev.428bfc8e397e.jar",
          "url": "wabt-0.3.0-dev.428bfc8e397e.jar",
          "size": 513688,
          "sha512": "47ec1f77ac202f6d1d2909f1887943f5e097814535b3c849d9f72f327f8f0bd2f8d539526c11b1d541df9912f9828b2e8f9a4fd49f4d4fc6c89fa908d7f3ad39",
          "sha256": "315839f71e5b9a68475c8d43b50c92d18833cf5dd9f7d486668a47e1a5094a1b",
          "sha1": "85110bd07b064585effe22bb3330d7e514570d12",
          "md5": "9edd3324192fab14df5ee807b06fb57d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-bom",
          "version": {
            "requires": "9.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.roastedroot",
          "module": "zerofs",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "log",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wabt-0.3.0-dev.428bfc8e397e.jar",
          "url": "wabt-0.3.0-dev.428bfc8e397e.jar",
          "size": 513688,
          "sha512": "47ec1f77ac202f6d1d2909f1887943f5e097814535b3c849d9f72f327f8f0bd2f8d539526c11b1d541df9912f9828b2e8f9a4fd49f4d4fc6c89fa908d7f3ad39",
          "sha256": "315839f71e5b9a68475c8d43b50c92d18833cf5dd9f7d486668a47e1a5094a1b",
          "sha1": "85110bd07b064585effe22bb3330d7e514570d12",
          "md5": "9edd3324192fab14df5ee807b06fb57d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wabt-0.3.0-dev.428bfc8e397e-sources.jar",
          "url": "wabt-0.3.0-dev.428bfc8e397e-sources.jar",
          "size": 497302,
          "sha512": "1bcb8bda2aa426746f97d7548d327d81a30343301edb2415927418b31f8a2f23b64f90eb1417e313b99ff41600fde72cff56b23f419dc9b64a0da78cc2f445ba",
          "sha256": "d9680cbd1dc28d775914b80818008e5b69d81a95483de9e4a4ed931581ed3c27",
          "sha1": "1f14aa2e47161fc286f310f7ee8c43a3c0fa8877",
          "md5": "b3cd959389c83e261e2a0d100020b8ba"
        }
      ]
    }
  ]
}
