{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "codegen",
    "version": "0.3.0-dev.59c0bdcaad2a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-0.3.0-dev.59c0bdcaad2a.jar",
          "url": "codegen-0.3.0-dev.59c0bdcaad2a.jar",
          "size": 21881,
          "sha512": "689f68b0ddc0dd53867775272d25119f3e7bc8f570a655b59a783db08b911dffe770047b42851d41e7b8091daaa85f88ee093beda61613a2173da5d2b74c2b4f",
          "sha256": "1a2b9ee3feb5c69e04fe34f827b98e72cfa6ead6abcd8ecdb2aa88ee68456d86",
          "sha1": "2eadce457ca4992d34378300a8f7a963ff4039c4",
          "md5": "f9d6cf7bd23a655c19bc9c9530713dd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-bom",
          "version": {
            "requires": "9.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "annotations",
          "version": {
            "requires": "0.3.0-dev.59c0bdcaad2a"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.59c0bdcaad2a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-0.3.0-dev.59c0bdcaad2a.jar",
          "url": "codegen-0.3.0-dev.59c0bdcaad2a.jar",
          "size": 21881,
          "sha512": "689f68b0ddc0dd53867775272d25119f3e7bc8f570a655b59a783db08b911dffe770047b42851d41e7b8091daaa85f88ee093beda61613a2173da5d2b74c2b4f",
          "sha256": "1a2b9ee3feb5c69e04fe34f827b98e72cfa6ead6abcd8ecdb2aa88ee68456d86",
          "sha1": "2eadce457ca4992d34378300a8f7a963ff4039c4",
          "md5": "f9d6cf7bd23a655c19bc9c9530713dd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-0.3.0-dev.59c0bdcaad2a-sources.jar",
          "url": "codegen-0.3.0-dev.59c0bdcaad2a-sources.jar",
          "size": 5648,
          "sha512": "cc2359ed4b6863389d848a74594f8630e2122c6a04f0bc43581863e562071f5ed634278eab77d9028753a6d60da309adb947b28fb22904dc972092e38192b440",
          "sha256": "b63f7f924f253002b5a5d19dea49963f4174d5c412de2812f3909273c123aa2e",
          "sha1": "0be0588a104a6d49aaab2b17def51e4344340c29",
          "md5": "4040b9aed26980ec8821d398dad46dc8"
        }
      ]
    }
  ]
}
