{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasi-preview3/0.3.0-dev.9facec7b2186/wasi-preview3-0.3.0-dev.9facec7b2186.module",
    "group": "uk.shusek.krwa",
    "module": "wasi-preview3",
    "version": "0.3.0-dev.9facec7b2186",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.9facec7b2186"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-iosArm64Main-0.3.0-dev.9facec7b2186.klib",
          "url": "wasi-preview3-iosarm64-0.3.0-dev.9facec7b2186.klib",
          "size": 51236,
          "sha512": "85b4703acb46721779964ce04a999c558dcf7b4b4ea3b001b4e3b3465900ec37c71a3463902a20d6fc10225ab7f642185fe385cfa2c15422b1decac49a6167c4",
          "sha256": "f0b39243435012d696744f2bb4396a75740e199b46caad86027f07782bf50f88",
          "sha1": "9ca85cbe24e11b68cd0ba299e98102b30ac8b072",
          "md5": "fbc9ec8e219039af873e832b2107636a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "wasi-preview3-iosarm64-0.3.0-dev.9facec7b2186-sources.jar",
          "url": "wasi-preview3-iosarm64-0.3.0-dev.9facec7b2186-sources.jar",
          "size": 10175,
          "sha512": "3f73586a63292c190f3f49081613789801e18ae49013dadff9459d8954559c146692dc1d850aef6692db914b296f2e44a1e90b4dda292ab272cae4a402fc3771",
          "sha256": "ec16e52826a01b4d02c6fb12daf8f586e0fb4c3c932d610e1fecadfeebde3a58",
          "sha1": "5847bb39e813851b23ff487bd08d78ce1c4b8200",
          "md5": "db2ceda50ca4f5e3dbf1bad70fa71962"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.9facec7b2186"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-iosarm64-0.3.0-dev.9facec7b2186-metadata.jar",
          "url": "wasi-preview3-iosarm64-0.3.0-dev.9facec7b2186-metadata.jar",
          "size": 4530,
          "sha512": "8f0bba011a56e9b6313c8997e6949b67c8260acd4a118900d71f054a527fab80f171bcffb754eba5b331e0014ec973e1c397ef5bfc6f12095dedf5fef8ee7eb6",
          "sha256": "a8a43f1f534fc9cc34fd8121663f684b4f571a90c1ea53af1dce03f812976883",
          "sha1": "c991bb31f888cb5d977a7b784d5daef233923f56",
          "md5": "f001c0bac95a7221919d42cfaa780fb4"
        }
      ]
    }
  ]
}
