{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "component-model-tooling",
    "version": "0.3.0-dev.90cee2d2dbef",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-tooling-0.3.0-dev.90cee2d2dbef.jar",
          "url": "component-model-tooling-0.3.0-dev.90cee2d2dbef.jar",
          "size": 8462,
          "sha512": "a38390b6622847f60040f1c34a6de00c86463f5631de27502c0d29edce9c9e78ee06cf09678a9d025b2554de924de4bcf566c938d49eb2a2f7aead5519d75a68",
          "sha256": "8f12883c95a08bc48cea52b4a263a01755bd1c88a27274e1016ea16aee7c6035",
          "sha1": "6d7e2fc77f86424dac07be4f940791b3ad2e2629",
          "md5": "2998158851e4385501ca6584ac53ca59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-bom",
          "version": {
            "requires": "9.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "log",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm-tools",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-tooling-0.3.0-dev.90cee2d2dbef.jar",
          "url": "component-model-tooling-0.3.0-dev.90cee2d2dbef.jar",
          "size": 8462,
          "sha512": "a38390b6622847f60040f1c34a6de00c86463f5631de27502c0d29edce9c9e78ee06cf09678a9d025b2554de924de4bcf566c938d49eb2a2f7aead5519d75a68",
          "sha256": "8f12883c95a08bc48cea52b4a263a01755bd1c88a27274e1016ea16aee7c6035",
          "sha1": "6d7e2fc77f86424dac07be4f940791b3ad2e2629",
          "md5": "2998158851e4385501ca6584ac53ca59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "component-model-tooling-0.3.0-dev.90cee2d2dbef-sources.jar",
          "url": "component-model-tooling-0.3.0-dev.90cee2d2dbef-sources.jar",
          "size": 3094,
          "sha512": "dc5723aeaee59285f049ccd811a95a2d3887e6c1939342642585be12ce9938d360718f440722f02cde2ce29eb6c2279810906813557225fcb5ef14a52f63b26c",
          "sha256": "7bc0f24c1a92713c098c4600c137ccff3552806e87c085fcc2e464cc66567682",
          "sha1": "02659888cc2b841b6dd819fc453161665080f738",
          "md5": "153e1668898188318c0074ee6907e6a8"
        }
      ]
    }
  ]
}
