{
  "formatVersion": "1.1",
  "component": {
    "url": "../../component-model/0.3.0-dev.8347044dd14e/component-model-0.3.0-dev.8347044dd14e.module",
    "group": "uk.shusek.krwa",
    "module": "component-model",
    "version": "0.3.0-dev.8347044dd14e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.8347044dd14e.jar",
          "url": "component-model-jvm-0.3.0-dev.8347044dd14e.jar",
          "size": 1640345,
          "sha512": "f4f6828c1c0270c6677e2877a1e9b26b640f6e280966956343008700df38e34ab69dc9a064b904c81db348fdfa32685e2cafe784ee75535d026c0acdb705048d",
          "sha256": "83562b389efb3faba40240762b73eeab20ffdb1bd905c1c0924e9fe4cd04b900",
          "sha1": "e41c6bca330f97cb255fc45ee26cc332f94ad93a",
          "md5": "ebcc487477b14eb8f7cc5983933fd41c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "log",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.8347044dd14e.jar",
          "url": "component-model-jvm-0.3.0-dev.8347044dd14e.jar",
          "size": 1640345,
          "sha512": "f4f6828c1c0270c6677e2877a1e9b26b640f6e280966956343008700df38e34ab69dc9a064b904c81db348fdfa32685e2cafe784ee75535d026c0acdb705048d",
          "sha256": "83562b389efb3faba40240762b73eeab20ffdb1bd905c1c0924e9fe4cd04b900",
          "sha1": "e41c6bca330f97cb255fc45ee26cc332f94ad93a",
          "md5": "ebcc487477b14eb8f7cc5983933fd41c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.8347044dd14e-sources.jar",
          "url": "component-model-jvm-0.3.0-dev.8347044dd14e-sources.jar",
          "size": 196282,
          "sha512": "34791233ebdbce8be85692a18ae02a9466eff07915dc9a7cd1bb3c7cf2f3b2c765df2cacc7804fa2634ca621fcb9c7a5fa1569979c1503d549cfe2ccab49d41f",
          "sha256": "7123ec2bfd32a25fde12d7b9ab34223112fe28d79b5085368a0ad8bbbaad7326",
          "sha1": "57ea3d13e7840b029d0e9a1ad2e1b85b2e2b2eb3",
          "md5": "37ca833beb2b9cc56dee4f6f05349081"
        }
      ]
    }
  ]
}
