{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasm/0.3.0-dev.ce74cc1b5a6f/wasm-0.3.0-dev.ce74cc1b5a6f.module",
    "group": "uk.shusek.krwa",
    "module": "wasm",
    "version": "0.3.0-dev.ce74cc1b5a6f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "wasm-iosSimulatorArm64Main-0.3.0-dev.ce74cc1b5a6f.klib",
          "url": "wasm-iossimulatorarm64-0.3.0-dev.ce74cc1b5a6f.klib",
          "size": 370968,
          "sha512": "0fbab85174d63ea435f643aef5e3205f4a5e657e95f03ad9aab21dc2e8111d88183b67defc6d13b886ed60876fb4c09bf7ec2bae1dbf663881f87f4dedf7d23a",
          "sha256": "d30fa4a6c49363987d7c87c9a099195ff31565551e5e1723fe0aeee7259411ea",
          "sha1": "a704294c01d71245b2ea242df1ea9d95e7516116",
          "md5": "7b69d91840f8730a7e0e744d2ff22afb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "wasm-iossimulatorarm64-0.3.0-dev.ce74cc1b5a6f-sources.jar",
          "url": "wasm-iossimulatorarm64-0.3.0-dev.ce74cc1b5a6f-sources.jar",
          "size": 82801,
          "sha512": "6dac747f4973b7f99bf5e885caddeccd39e8784e16efaac44ad138d7d04529e9fd7c8078b2d918a1daac8fc053fc577e3c06437ba549e70da0b32a84a50fd5ad",
          "sha256": "1def46b6feb1621c8659a2a272e42d2249d73032b81d2eb9fb341fdaf0c6a536",
          "sha1": "bae5901421489bdc1f99e2168fc3050e3b19a454",
          "md5": "9a6f81b8ab5973a09e97d73eab7dbe01"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "wasm-iossimulatorarm64-0.3.0-dev.ce74cc1b5a6f-metadata.jar",
          "url": "wasm-iossimulatorarm64-0.3.0-dev.ce74cc1b5a6f-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
