{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "component-model-gradle-plugin",
    "version": "0.3.0-dev.9facec7b2186",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-gradle-plugin-0.3.0-dev.9facec7b2186.jar",
          "url": "component-model-gradle-plugin-0.3.0-dev.9facec7b2186.jar",
          "size": 73529,
          "sha512": "63bde36f345538a3ac5ecc92531b87bd532e093025a9baedc213822ecb73558828a81476713a30a3eb4ca77c05eb9d0a2f75f6e7aaec7f9c89905c84fc304348",
          "sha256": "f70ff3a8db2bf180aeb8603485c376815d3198e99ece04d8236f0ed1cb5ee279",
          "sha1": "fb66a8056ab3f56693d6b5ab93081048298c3ed3",
          "md5": "f03b1b5997421392ce371ac926748d72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.9facec7b2186"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "component-model-tooling",
          "version": {
            "requires": "0.3.0-dev.9facec7b2186"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-gradle-plugin-0.3.0-dev.9facec7b2186.jar",
          "url": "component-model-gradle-plugin-0.3.0-dev.9facec7b2186.jar",
          "size": 73529,
          "sha512": "63bde36f345538a3ac5ecc92531b87bd532e093025a9baedc213822ecb73558828a81476713a30a3eb4ca77c05eb9d0a2f75f6e7aaec7f9c89905c84fc304348",
          "sha256": "f70ff3a8db2bf180aeb8603485c376815d3198e99ece04d8236f0ed1cb5ee279",
          "sha1": "fb66a8056ab3f56693d6b5ab93081048298c3ed3",
          "md5": "f03b1b5997421392ce371ac926748d72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "component-model-gradle-plugin-0.3.0-dev.9facec7b2186-sources.jar",
          "url": "component-model-gradle-plugin-0.3.0-dev.9facec7b2186-sources.jar",
          "size": 10479,
          "sha512": "0a4f20cc1abf472ad20319faf9640f23c45e76b0155cea137c4194d67ccd8bf5411839a11f9718fe6a6714eccd68da6f143c4d047d051b0071b0d94a255c41e6",
          "sha256": "9657334d9107126ce0a90315780d152995b5627db50be881933ee55150db25cf",
          "sha1": "ade02e436f430f19181661f2f95dc1a5a22bcce4",
          "md5": "e82d40bdb5ba1ad11482f19221371be5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "component-model-gradle-plugin-0.3.0-dev.9facec7b2186-javadoc.jar",
          "url": "component-model-gradle-plugin-0.3.0-dev.9facec7b2186-javadoc.jar",
          "size": 1033,
          "sha512": "c568aeab567d1d1f8a2c3fa1d3f00998e4dd7368bcb355120a20f347a36ff61ce28f1fac12a02dc4b6088df4768eba4dd25be7a3f2b9e6e2eecf7b0446563a8e",
          "sha256": "bfcbe099cc78cb83956caed2538d3dbf6fecea876285e37c78f733b390db7bb2",
          "sha1": "25b44970eb81c7b30b9a75eae361c8f34c14e6fd",
          "md5": "e4f10b7cecb57a7d967c37297fe5e6fd"
        }
      ]
    }
  ]
}
