version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-coroutines-*"
        versions:
          - "1.11.0"
  - package-ecosystem: gradle
    directory: "/samples/android-tests"
    schedule:
      interval: weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
