version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: "/samples/android-tests"
    schedule:
      interval: weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
