{
  "formatVersion": "1.1",
  "component": {
    "url": "../../component-model/0.3.0-dev.e3ca3a2569a9/component-model-0.3.0-dev.e3ca3a2569a9.module",
    "group": "uk.shusek.krwa",
    "module": "component-model",
    "version": "0.3.0-dev.e3ca3a2569a9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.e3ca3a2569a9.jar",
          "url": "component-model-jvm-0.3.0-dev.e3ca3a2569a9.jar",
          "size": 1637393,
          "sha512": "9498cf9a99eae0822764cc811cf6ae84c6c03e39403890316234c526aac7b266f606716f537c36f898813c9a6892e11506b352158d5e4df3557d5cb821834392",
          "sha256": "dd00ea131937c1348c4d726f506a89c1daaf76b643b2117fc8267b4aa7444f08",
          "sha1": "3c426de70e59346a9e8dc76da1084387f8b8273f",
          "md5": "667db219654c5a8bbe8ce8a8e7edac8d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "log",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.e3ca3a2569a9.jar",
          "url": "component-model-jvm-0.3.0-dev.e3ca3a2569a9.jar",
          "size": 1637393,
          "sha512": "9498cf9a99eae0822764cc811cf6ae84c6c03e39403890316234c526aac7b266f606716f537c36f898813c9a6892e11506b352158d5e4df3557d5cb821834392",
          "sha256": "dd00ea131937c1348c4d726f506a89c1daaf76b643b2117fc8267b4aa7444f08",
          "sha1": "3c426de70e59346a9e8dc76da1084387f8b8273f",
          "md5": "667db219654c5a8bbe8ce8a8e7edac8d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.e3ca3a2569a9-sources.jar",
          "url": "component-model-jvm-0.3.0-dev.e3ca3a2569a9-sources.jar",
          "size": 195892,
          "sha512": "d28e8220f59cbc4c5fd49ac8dc871fc5d93ef77cb1bda0eef4b88261f6ee5a78ddf3afe7cc93157e20feaaf4d400afcf601ed8c8ea19429d29e3e0e10f09f0c0",
          "sha256": "1af2d1677f73254a197ef16fe52f0fde6736c3b1d1a9abe41bb321391702d5c0",
          "sha1": "18194d29b925e83fc264da2ccb8e6ad5d6690c2d",
          "md5": "25b7b86af0244207752fbddbe7f118fc"
        }
      ]
    }
  ]
}
