{
  "formatVersion": "1.1",
  "component": {
    "url": "../../component-model/0.3.0-dev.e3ca3a2569a9/component-model-0.3.0-dev.e3ca3a2569a9.module",
    "group": "uk.shusek.krwa",
    "module": "component-model",
    "version": "0.3.0-dev.e3ca3a2569a9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-iosSimulatorArm64Main-0.3.0-dev.e3ca3a2569a9.klib",
          "url": "component-model-iossimulatorarm64-0.3.0-dev.e3ca3a2569a9.klib",
          "size": 909538,
          "sha512": "c53ff2e463e116193f7db12339ecc2fb288e5bb8da6a5d959e3c8fc649dc61dfbcdbc3d866e39e2d05936c077f708388d134657b500a3adc7a7fd3eeaec924b6",
          "sha256": "2dadeb7ab97239f7fb84e2f383644d7ab33553676a392008f2e2469802694ba7",
          "sha1": "f124ea93a3fb96bae9d2de11bd4cc4951c8859f8",
          "md5": "e849181736ed07075207322d138fcd44"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "component-model-iossimulatorarm64-0.3.0-dev.e3ca3a2569a9-sources.jar",
          "url": "component-model-iossimulatorarm64-0.3.0-dev.e3ca3a2569a9-sources.jar",
          "size": 149363,
          "sha512": "bb7ab818aa1b9cd17b0871004d0acef58211ac7a551cb5637cf37dd06efb6fb407497dfd2b95a09375c8974a59e4ecbc718a6ab110ace7c2b152257639b0049a",
          "sha256": "254cc01f9cc071550b82f5703b08af0a27346df5e546204f76438b4ee0b93ec7",
          "sha1": "01b38ac8ad3a25321113eb12c4eba64b4fad3971",
          "md5": "aef815d20396682d25c700b1d26a7497"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-iossimulatorarm64-0.3.0-dev.e3ca3a2569a9-metadata.jar",
          "url": "component-model-iossimulatorarm64-0.3.0-dev.e3ca3a2569a9-metadata.jar",
          "size": 8184,
          "sha512": "06bf6a563e4306b85fd9d4502a3e0b71828d04818222f633809bfafa462d5da6d542e1bb994bc6225c020ccfcdd05c43b07bd02ebaac77a80e913820465b53cc",
          "sha256": "25f1c1ddc1afcaa9e1c204568dd911ad6fa087d9c90d843f9e68d1612bd5dddf",
          "sha1": "9b804789a1b0e487736c44256b76de1e5bc90c07",
          "md5": "9e52bb014a339a3b68d7fa423bc227bf"
        }
      ]
    }
  ]
}
