{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotations/0.3.0-dev.08b8ff4fbe4a/annotations-0.3.0-dev.08b8ff4fbe4a.module",
    "group": "uk.shusek.krwa",
    "module": "annotations",
    "version": "0.3.0-dev.08b8ff4fbe4a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-wasm-js-0.3.0-dev.08b8ff4fbe4a.klib",
          "url": "annotations-wasm-js-0.3.0-dev.08b8ff4fbe4a.klib",
          "size": 8130,
          "sha512": "aeefe4a4faff988e29502121f2c8d322e6e6c79a72de8c38af534524c372fd3720ba9537427107c534ab6249cc6b17fec7be9bc5f558f0c5a4a3e1ca6f7486ab",
          "sha256": "8bdbe043d1c0f2652318660567710836d59c30f76ee068ff905f1d2972df255e",
          "sha1": "f84aedb46ecb4a4bdf0a495cd6dc9f27c67cb50e",
          "md5": "224f77fddf031909d549da2996613a5b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-wasm-js-0.3.0-dev.08b8ff4fbe4a.klib",
          "url": "annotations-wasm-js-0.3.0-dev.08b8ff4fbe4a.klib",
          "size": 8130,
          "sha512": "aeefe4a4faff988e29502121f2c8d322e6e6c79a72de8c38af534524c372fd3720ba9537427107c534ab6249cc6b17fec7be9bc5f558f0c5a4a3e1ca6f7486ab",
          "sha256": "8bdbe043d1c0f2652318660567710836d59c30f76ee068ff905f1d2972df255e",
          "sha1": "f84aedb46ecb4a4bdf0a495cd6dc9f27c67cb50e",
          "md5": "224f77fddf031909d549da2996613a5b"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "annotations-wasm-js-0.3.0-dev.08b8ff4fbe4a-sources.jar",
          "url": "annotations-wasm-js-0.3.0-dev.08b8ff4fbe4a-sources.jar",
          "size": 2453,
          "sha512": "6d6f4aae2d93a926473bb47df523a8ce41a65da675f99eed5717ce20998b4ae4120488186444b603439cb94260705446ee2dff5528962db6eec5a1e5120eaa6e",
          "sha256": "ed5d93d4836238ffaff5db35a28a36a7df393f5528810c443e4a9c0a1e0250a6",
          "sha1": "f3645b27317c7a20ffc7941724fb24f9a2d38585",
          "md5": "1bae3d7db028bd3fb5d8c41dd8c4b1b3"
        }
      ]
    }
  ]
}
