{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasm/0.3.0-dev.428bfc8e397e/wasm-0.3.0-dev.428bfc8e397e.module",
    "group": "uk.shusek.krwa",
    "module": "wasm",
    "version": "0.3.0-dev.428bfc8e397e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasm-jvm-0.3.0-dev.428bfc8e397e.jar",
          "url": "wasm-jvm-0.3.0-dev.428bfc8e397e.jar",
          "size": 357211,
          "sha512": "7ff61098e93a9a99aa7975498fc1753c7ae5127bc878efaf2cc476f4d7059c6bfa2d934777a783a1af870e7589805dc3d8e1d792c0789654eb061bb881986373",
          "sha256": "015522c66f1579d3bc005a0de1dde901d7b4b39c9684b13d903fae44d68865e0",
          "sha1": "fad4cafdd7808133f731e76c56ddd47147ca674c",
          "md5": "527cb6c4f7776ea6d02486eac7360593"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "wasm-jvm-0.3.0-dev.428bfc8e397e.jar",
          "url": "wasm-jvm-0.3.0-dev.428bfc8e397e.jar",
          "size": 357211,
          "sha512": "7ff61098e93a9a99aa7975498fc1753c7ae5127bc878efaf2cc476f4d7059c6bfa2d934777a783a1af870e7589805dc3d8e1d792c0789654eb061bb881986373",
          "sha256": "015522c66f1579d3bc005a0de1dde901d7b4b39c9684b13d903fae44d68865e0",
          "sha1": "fad4cafdd7808133f731e76c56ddd47147ca674c",
          "md5": "527cb6c4f7776ea6d02486eac7360593"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "wasm-jvm-0.3.0-dev.428bfc8e397e-sources.jar",
          "url": "wasm-jvm-0.3.0-dev.428bfc8e397e-sources.jar",
          "size": 88156,
          "sha512": "c253277c37c3a30816b3ac7063dfb20f448af95c41722dca4c686a1885668ca64bf3369ccb46b722554ff0e8b2b1b3d4d94d41a0e23bfd12aefef5c82cc01a7d",
          "sha256": "2ca9b3d7d1dd6114ecd301b49d55b7f72f5f58d0fb8329af85c4ed3df2ca2ca2",
          "sha1": "4273748a252a6a17000fb9fbfc18912a134b1a21",
          "md5": "1d89f8d5059e370b175d0d53e10b7071"
        }
      ]
    }
  ]
}
