{
  "formatVersion": "1.1",
  "component": {
    "url": "../../component-model/0.3.0-dev.dd7a6fdf625a/component-model-0.3.0-dev.dd7a6fdf625a.module",
    "group": "uk.shusek.krwa",
    "module": "component-model",
    "version": "0.3.0-dev.dd7a6fdf625a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.dd7a6fdf625a"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.dd7a6fdf625a"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.dd7a6fdf625a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.dd7a6fdf625a.jar",
          "url": "component-model-jvm-0.3.0-dev.dd7a6fdf625a.jar",
          "size": 1639191,
          "sha512": "9393e1a8ae02e68135ae38d35ad2cc449f7ec525e97972bfd71e5d95248dd7981749be4468684da275f39df0e587e7853ef60c72b80e401afc6d4e76b37a3645",
          "sha256": "fd1fd5171939c5f711df64d4e86623d47ee90017cc324f55c1d180b0e036c88d",
          "sha1": "13911bdd57fc264e101a6a65e3e669c7813cf1ba",
          "md5": "6c696d8f4753489b6f410a8f4138fc02"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.dd7a6fdf625a"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.dd7a6fdf625a"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.dd7a6fdf625a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "log",
          "version": {
            "requires": "0.3.0-dev.dd7a6fdf625a"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.dd7a6fdf625a.jar",
          "url": "component-model-jvm-0.3.0-dev.dd7a6fdf625a.jar",
          "size": 1639191,
          "sha512": "9393e1a8ae02e68135ae38d35ad2cc449f7ec525e97972bfd71e5d95248dd7981749be4468684da275f39df0e587e7853ef60c72b80e401afc6d4e76b37a3645",
          "sha256": "fd1fd5171939c5f711df64d4e86623d47ee90017cc324f55c1d180b0e036c88d",
          "sha1": "13911bdd57fc264e101a6a65e3e669c7813cf1ba",
          "md5": "6c696d8f4753489b6f410a8f4138fc02"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.dd7a6fdf625a-sources.jar",
          "url": "component-model-jvm-0.3.0-dev.dd7a6fdf625a-sources.jar",
          "size": 195892,
          "sha512": "d28e8220f59cbc4c5fd49ac8dc871fc5d93ef77cb1bda0eef4b88261f6ee5a78ddf3afe7cc93157e20feaaf4d400afcf601ed8c8ea19429d29e3e0e10f09f0c0",
          "sha256": "1af2d1677f73254a197ef16fe52f0fde6736c3b1d1a9abe41bb321391702d5c0",
          "sha1": "18194d29b925e83fc264da2ccb8e6ad5d6690c2d",
          "md5": "25b7b86af0244207752fbddbe7f118fc"
        }
      ]
    }
  ]
}
