{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "cli-experimental",
    "version": "0.3.0-dev.f3c34df3a402",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.f3c34df3a402.jar",
          "url": "cli-experimental-0.3.0-dev.f3c34df3a402.jar",
          "size": 6885,
          "sha512": "49bca306d3d260b9ddd705bbd530b338b219b58b798a5a3cfef55b3b4c893c68ff75ba1b89d15370c946efc2248a2dd9d37c541e1ccf57794f47f4b34c0bb32a",
          "sha256": "ac8b85d3c653efd771f5ee029d71a226c08b0354e65fee328bcc2fbe944efdda",
          "sha1": "5c7d7d4e64f66ab038b7f4e12e01a0dd6a13690d",
          "md5": "603dbb3a96887d004fa6626c854c0ab9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-bom",
          "version": {
            "requires": "9.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.7"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.f3c34df3a402"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.f3c34df3a402"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.f3c34df3a402"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.f3c34df3a402.jar",
          "url": "cli-experimental-0.3.0-dev.f3c34df3a402.jar",
          "size": 6885,
          "sha512": "49bca306d3d260b9ddd705bbd530b338b219b58b798a5a3cfef55b3b4c893c68ff75ba1b89d15370c946efc2248a2dd9d37c541e1ccf57794f47f4b34c0bb32a",
          "sha256": "ac8b85d3c653efd771f5ee029d71a226c08b0354e65fee328bcc2fbe944efdda",
          "sha1": "5c7d7d4e64f66ab038b7f4e12e01a0dd6a13690d",
          "md5": "603dbb3a96887d004fa6626c854c0ab9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.f3c34df3a402-sources.jar",
          "url": "cli-experimental-0.3.0-dev.f3c34df3a402-sources.jar",
          "size": 2878,
          "sha512": "50e9bf370d195609b0a1db0bb4d96ff6a6c66c63d491364b211692bc5bd0ebf465688f5fecc27ea9542e3867acd852e0bd6768c125b8f743963370bf19210586",
          "sha256": "bad212958edfa5e097f8e77b5ffb21178fb1f1a9f9303054a60237e1cd7e8abd",
          "sha1": "efe6069639f6dbb85df3a3ef02ac40c06055bf74",
          "md5": "bfe98afa8bbacfe40c2cda523aacb34a"
        }
      ]
    }
  ]
}
