{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "component-model-tooling",
    "version": "0.3.0-dev.59c0bdcaad2a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.59c0bdcaad2a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-tooling-0.3.0-dev.59c0bdcaad2a.jar",
          "url": "component-model-tooling-0.3.0-dev.59c0bdcaad2a.jar",
          "size": 8462,
          "sha512": "6ebf92f2ebc9f0b780f6d53a7fc888389b58021e8eb248f11ee58f97d2377ea4d686166db2010ff7d672b3c78ac917974b37568d0e39970af64c8e38b72dea07",
          "sha256": "52a2de4f61772b33b7600a3342cfc4a6b78939373b6b32a5c0d095cfb1758d43",
          "sha1": "17089d4364c1a6d81684f5807ec5df6cd5dc3ff4",
          "md5": "96275774472fa706b0e4f05f1fbf9423"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-bom",
          "version": {
            "requires": "9.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "log",
          "version": {
            "requires": "0.3.0-dev.59c0bdcaad2a"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.59c0bdcaad2a"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.59c0bdcaad2a"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.59c0bdcaad2a"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm-tools",
          "version": {
            "requires": "0.3.0-dev.59c0bdcaad2a"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.59c0bdcaad2a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-tooling-0.3.0-dev.59c0bdcaad2a.jar",
          "url": "component-model-tooling-0.3.0-dev.59c0bdcaad2a.jar",
          "size": 8462,
          "sha512": "6ebf92f2ebc9f0b780f6d53a7fc888389b58021e8eb248f11ee58f97d2377ea4d686166db2010ff7d672b3c78ac917974b37568d0e39970af64c8e38b72dea07",
          "sha256": "52a2de4f61772b33b7600a3342cfc4a6b78939373b6b32a5c0d095cfb1758d43",
          "sha1": "17089d4364c1a6d81684f5807ec5df6cd5dc3ff4",
          "md5": "96275774472fa706b0e4f05f1fbf9423"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "component-model-tooling-0.3.0-dev.59c0bdcaad2a-sources.jar",
          "url": "component-model-tooling-0.3.0-dev.59c0bdcaad2a-sources.jar",
          "size": 3094,
          "sha512": "ddd8ac0c48a61252566a69bc1a56ceba5f051b8d751173bbd9f5e9906dd4f8d030be31a2eda283f86eb309c06a68e21da808b4aadb15349de867d1ce4a97836b",
          "sha256": "9cc6b19d416383661a8c449280ec81e8d246bace5120f0adf3b30fb597708bf4",
          "sha1": "60dd00419520afbcb54c3883679f871b1155c7fe",
          "md5": "f9f6d008f7d6eba453ddb4ea9ac3048a"
        }
      ]
    }
  ]
}
