{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasi-preview3/0.3.0-dev.e3ca3a2569a9/wasi-preview3-0.3.0-dev.e3ca3a2569a9.module",
    "group": "uk.shusek.krwa",
    "module": "wasi-preview3",
    "version": "0.3.0-dev.e3ca3a2569a9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-wasm-js-0.3.0-dev.e3ca3a2569a9.klib",
          "url": "wasi-preview3-wasm-js-0.3.0-dev.e3ca3a2569a9.klib",
          "size": 97951,
          "sha512": "78bb9dfd09c58333fbbbf4e81c247014d8513f765b5cb161a38e58ee87aa7307ceaf4205058aff8229317bf0c11f0c4285dfb60818f5ca26a474ba9564efa54b",
          "sha256": "9516d3638f6350917446f315d17a7ccec8ba153fb677f8d2df78524bb991fe62",
          "sha1": "4ec51ba05e90908d432da44340656cbe3264d6fb",
          "md5": "54d75ec92d117b6fa47f8ab40526dc0a"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-wasm-js-0.3.0-dev.e3ca3a2569a9.klib",
          "url": "wasi-preview3-wasm-js-0.3.0-dev.e3ca3a2569a9.klib",
          "size": 97951,
          "sha512": "78bb9dfd09c58333fbbbf4e81c247014d8513f765b5cb161a38e58ee87aa7307ceaf4205058aff8229317bf0c11f0c4285dfb60818f5ca26a474ba9564efa54b",
          "sha256": "9516d3638f6350917446f315d17a7ccec8ba153fb677f8d2df78524bb991fe62",
          "sha1": "4ec51ba05e90908d432da44340656cbe3264d6fb",
          "md5": "54d75ec92d117b6fa47f8ab40526dc0a"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "wasi-preview3-wasm-js-0.3.0-dev.e3ca3a2569a9-sources.jar",
          "url": "wasi-preview3-wasm-js-0.3.0-dev.e3ca3a2569a9-sources.jar",
          "size": 17959,
          "sha512": "0912bb19992d10feb2b7d43e535484cda4095fab659dc07b1a78ffcde8c348ec726dd50344a6eb833a07a7b8d44d4f4def2387bde69ed72e8c565cb3f1ccd178",
          "sha256": "86d097600f071a36a6cc2713e6be30055971613615fc3e54c9c68c49f17a188e",
          "sha1": "08783e471572b73ecb9062d9afcc296f552f1c56",
          "md5": "c57dfd15eaae54d2e58788f80c69e2e4"
        }
      ]
    }
  ]
}
