{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "wasm",
    "version": "0.3.0-dev.90cee2d2dbef",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "wasm-metadata-0.3.0-dev.90cee2d2dbef.jar",
          "url": "wasm-0.3.0-dev.90cee2d2dbef.jar",
          "size": 62383,
          "sha512": "da82a125b5fb9f40065cfe8f67cfa55bb5bb7f8302a7585a863ed35b7ccc907ffac944b6403af5a5ec061554f88eadaa06553b1ba79ec27ab5be72461e6717a6",
          "sha256": "2dfecd2eeedd65b00ab5348c64672614f7f67182bb4dbf24f9d8c8bea0908140",
          "sha1": "b1ae5515a3de1c9d5febbd26f116d8fa4a7d4550",
          "md5": "22e9b1334c09e71f55c65a1606edc2cf"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "wasm-kotlin-0.3.0-dev.90cee2d2dbef-sources.jar",
          "url": "wasm-0.3.0-dev.90cee2d2dbef-sources.jar",
          "size": 82801,
          "sha512": "6dac747f4973b7f99bf5e885caddeccd39e8784e16efaac44ad138d7d04529e9fd7c8078b2d918a1daac8fc053fc577e3c06437ba549e70da0b32a84a50fd5ad",
          "sha256": "1def46b6feb1621c8659a2a272e42d2249d73032b81d2eb9fb341fdaf0c6a536",
          "sha1": "bae5901421489bdc1f99e2168fc3050e3b19a454",
          "md5": "9a6f81b8ab5973a09e97d73eab7dbe01"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasm-iosarm64/0.3.0-dev.90cee2d2dbef/wasm-iosarm64-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-iosarm64",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasm-iosarm64/0.3.0-dev.90cee2d2dbef/wasm-iosarm64-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-iosarm64",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasm-iosarm64/0.3.0-dev.90cee2d2dbef/wasm-iosarm64-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-iosarm64",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasm-iossimulatorarm64/0.3.0-dev.90cee2d2dbef/wasm-iossimulatorarm64-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-iossimulatorarm64",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasm-iossimulatorarm64/0.3.0-dev.90cee2d2dbef/wasm-iossimulatorarm64-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-iossimulatorarm64",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasm-iossimulatorarm64/0.3.0-dev.90cee2d2dbef/wasm-iossimulatorarm64-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-iossimulatorarm64",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wasm-jvm/0.3.0-dev.90cee2d2dbef/wasm-jvm-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-jvm",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wasm-jvm/0.3.0-dev.90cee2d2dbef/wasm-jvm-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-jvm",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wasm-jvm/0.3.0-dev.90cee2d2dbef/wasm-jvm-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-jvm",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wasm-wasm-js/0.3.0-dev.90cee2d2dbef/wasm-wasm-js-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-wasm-js",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wasm-wasm-js/0.3.0-dev.90cee2d2dbef/wasm-wasm-js-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-wasm-js",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wasm-wasm-js/0.3.0-dev.90cee2d2dbef/wasm-wasm-js-0.3.0-dev.90cee2d2dbef.module",
        "group": "uk.shusek.krwa",
        "module": "wasm-wasm-js",
        "version": "0.3.0-dev.90cee2d2dbef"
      }
    }
  ]
}
