{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasi/0.3.0-dev.ce74cc1b5a6f/wasi-0.3.0-dev.ce74cc1b5a6f.module",
    "group": "uk.shusek.krwa",
    "module": "wasi",
    "version": "0.3.0-dev.ce74cc1b5a6f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.ce74cc1b5a6f"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-jvm-0.3.0-dev.ce74cc1b5a6f.jar",
          "url": "wasi-jvm-0.3.0-dev.ce74cc1b5a6f.jar",
          "size": 119494,
          "sha512": "632e922ac931566a1f3b7eb8181cadc2dda0a3c42a991f516ce1bd084b0badf6d482cde16320d34fee194da34ec8aa4df635d95a9339cbd809b682354ed34cb8",
          "sha256": "006f42aaf745d83f42777d666f705a1471ceaae8bb0575811e5e1c75068502d4",
          "sha1": "f60fec0eb0419b9737f64e607a7290d93bbe7245",
          "md5": "209bf114f9fa05d28a8fa9342c5abfba"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.ce74cc1b5a6f"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "log",
          "version": {
            "requires": "0.3.0-dev.ce74cc1b5a6f"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.ce74cc1b5a6f"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "annotations",
          "version": {
            "requires": "0.3.0-dev.ce74cc1b5a6f"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-jvm-0.3.0-dev.ce74cc1b5a6f.jar",
          "url": "wasi-jvm-0.3.0-dev.ce74cc1b5a6f.jar",
          "size": 119494,
          "sha512": "632e922ac931566a1f3b7eb8181cadc2dda0a3c42a991f516ce1bd084b0badf6d482cde16320d34fee194da34ec8aa4df635d95a9339cbd809b682354ed34cb8",
          "sha256": "006f42aaf745d83f42777d666f705a1471ceaae8bb0575811e5e1c75068502d4",
          "sha1": "f60fec0eb0419b9737f64e607a7290d93bbe7245",
          "md5": "209bf114f9fa05d28a8fa9342c5abfba"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "wasi-jvm-0.3.0-dev.ce74cc1b5a6f-sources.jar",
          "url": "wasi-jvm-0.3.0-dev.ce74cc1b5a6f-sources.jar",
          "size": 30053,
          "sha512": "e8f912b62849d4d087843af1ecb92b594125b967393b4ff223eeac9694d7374535c03e410be705abb734617019d0d7f051d1eb1d075bfff0470ccb7e13225287",
          "sha256": "a0afab4dacba48b41f67fd9692ecd1dfbe3a4846643089d452581b4dddce6cbc",
          "sha1": "cf12d2491e4554d1f25660a1016ce1e6c80e130d",
          "md5": "21970ffc91565052d77dce3b53292f61"
        }
      ]
    }
  ]
}
