{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasi-preview3/0.3.0-dev.a852e327fbb9/wasi-preview3-0.3.0-dev.a852e327fbb9.module",
    "group": "uk.shusek.krwa",
    "module": "wasi-preview3",
    "version": "0.3.0-dev.a852e327fbb9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-wasm-js-0.3.0-dev.a852e327fbb9.klib",
          "url": "wasi-preview3-wasm-js-0.3.0-dev.a852e327fbb9.klib",
          "size": 99593,
          "sha512": "974b061d567fb1633ec39ae08a61019d6ebd3d5719366a85ced91f78e1690a9e59c5ecb12003931e3b6dd03bb9e256446c1af9691e7b603bde5eeb80406025b8",
          "sha256": "132094fd72d38f87c44e32f5cf2c920dc8764c83dfec6fac9552fa6863b93b3b",
          "sha1": "a9de13665eab62967b83f0ab271582fccb2069ee",
          "md5": "fcc026eaee00e55daa251ad31e827aaa"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-wasm-js-0.3.0-dev.a852e327fbb9.klib",
          "url": "wasi-preview3-wasm-js-0.3.0-dev.a852e327fbb9.klib",
          "size": 99593,
          "sha512": "974b061d567fb1633ec39ae08a61019d6ebd3d5719366a85ced91f78e1690a9e59c5ecb12003931e3b6dd03bb9e256446c1af9691e7b603bde5eeb80406025b8",
          "sha256": "132094fd72d38f87c44e32f5cf2c920dc8764c83dfec6fac9552fa6863b93b3b",
          "sha1": "a9de13665eab62967b83f0ab271582fccb2069ee",
          "md5": "fcc026eaee00e55daa251ad31e827aaa"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "wasi-preview3-wasm-js-0.3.0-dev.a852e327fbb9-sources.jar",
          "url": "wasi-preview3-wasm-js-0.3.0-dev.a852e327fbb9-sources.jar",
          "size": 18530,
          "sha512": "797e4c11433e1f13bad62bb13fb60958befcfd02b41068bea0060f103c33f9b2b79b33060caae00567d8c47d4c336a870aecd618085aecf8a3de1405aee3d945",
          "sha256": "c69e10e4a7f352efa2c8b146c1971dde14556bd38064a631d06a0c22dd241ef5",
          "sha1": "0c8085a5df348258d51c7d731947c8e40f508729",
          "md5": "26981bbfe36ded661d771b38d96cf375"
        }
      ]
    }
  ]
}
