{
  "formatVersion": "1.1",
  "component": {
    "url": "../../component-model/0.3.0-dev.a852e327fbb9/component-model-0.3.0-dev.a852e327fbb9.module",
    "group": "uk.shusek.krwa",
    "module": "component-model",
    "version": "0.3.0-dev.a852e327fbb9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-wasm-js-0.3.0-dev.a852e327fbb9.klib",
          "url": "component-model-wasm-js-0.3.0-dev.a852e327fbb9.klib",
          "size": 932215,
          "sha512": "aa14470a1e4425da033c611bc3bd987790df0f621b11d584fe8c48f1b6a6e2ea2b9a2940808e18292007f983ed352e98ec475678098607a0717c7cdd025e9123",
          "sha256": "ae5d994e816e918605c955520f6d956bac782466324db96e7f8172131c682975",
          "sha1": "607cb176dd814953d4b85004b4b2538bc8c685af",
          "md5": "6f34f3179d45d03e957d060ffaa318ca"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-wasm-js-0.3.0-dev.a852e327fbb9.klib",
          "url": "component-model-wasm-js-0.3.0-dev.a852e327fbb9.klib",
          "size": 932215,
          "sha512": "aa14470a1e4425da033c611bc3bd987790df0f621b11d584fe8c48f1b6a6e2ea2b9a2940808e18292007f983ed352e98ec475678098607a0717c7cdd025e9123",
          "sha256": "ae5d994e816e918605c955520f6d956bac782466324db96e7f8172131c682975",
          "sha1": "607cb176dd814953d4b85004b4b2538bc8c685af",
          "md5": "6f34f3179d45d03e957d060ffaa318ca"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "component-model-wasm-js-0.3.0-dev.a852e327fbb9-sources.jar",
          "url": "component-model-wasm-js-0.3.0-dev.a852e327fbb9-sources.jar",
          "size": 156949,
          "sha512": "1f3a871f58a2db35c4d14a78981aa0286c954b9dc214409dfc4f7890dc5549b8020abab8364573b08578704c9fbe0081d6234790e214e1c4d71fe890e74e2547",
          "sha256": "0a4714eedef6aab55f7d7a2de0b319611a84dcab3f3f5ce93b26f6e09a958fe1",
          "sha1": "9b864d9f8c6ff868785dd1160446d4ea130664e1",
          "md5": "ab15a3449e77a4c8529de33e7de55576"
        }
      ]
    }
  ]
}
