{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasi-preview3/0.3.0-dev.a852e327fbb9/wasi-preview3-0.3.0-dev.a852e327fbb9.module",
    "group": "uk.shusek.krwa",
    "module": "wasi-preview3",
    "version": "0.3.0-dev.a852e327fbb9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-iosSimulatorArm64Main-0.3.0-dev.a852e327fbb9.klib",
          "url": "wasi-preview3-iossimulatorarm64-0.3.0-dev.a852e327fbb9.klib",
          "size": 53433,
          "sha512": "1cc4980eb16bc6c04dd1f2bb88912b2ef357ecd9edccd1cc68c09d9faf4f5ee36d2e2957a0f518567a483c68aac079b56108c76f76a22cf913c333172dd07c9a",
          "sha256": "896bd4f371d9809519debcbc6e0ddbad33b61ed0216da857b77d66b68b5aa7b8",
          "sha1": "20a3af3f0d2aa45b38db873ce37a22d2ff50f532",
          "md5": "f7aea6fd682b2aeebd2895397a374920"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "wasi-preview3-iossimulatorarm64-0.3.0-dev.a852e327fbb9-sources.jar",
          "url": "wasi-preview3-iossimulatorarm64-0.3.0-dev.a852e327fbb9-sources.jar",
          "size": 10746,
          "sha512": "c38b251e32dc5c07f29198ffe0ab1ca5dbeba29b30a272ae62813f24ea608175c7fc716c5a038a0dbb361b693136095b7ff6c776149800ec0a718020fbd46c5e",
          "sha256": "bee1d80357c051ea6df38467a627ea445985249edb96d1c0af8c7ca808115171",
          "sha1": "4deb292058bec3508cbf97c4e3b3f5b9c1441b71",
          "md5": "1dc4aef3152ef0d06357374d370a5383"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-iossimulatorarm64-0.3.0-dev.a852e327fbb9-metadata.jar",
          "url": "wasi-preview3-iossimulatorarm64-0.3.0-dev.a852e327fbb9-metadata.jar",
          "size": 4530,
          "sha512": "8f0bba011a56e9b6313c8997e6949b67c8260acd4a118900d71f054a527fab80f171bcffb754eba5b331e0014ec973e1c397ef5bfc6f12095dedf5fef8ee7eb6",
          "sha256": "a8a43f1f534fc9cc34fd8121663f684b4f571a90c1ea53af1dce03f812976883",
          "sha1": "c991bb31f888cb5d977a7b784d5daef233923f56",
          "md5": "f001c0bac95a7221919d42cfaa780fb4"
        }
      ]
    }
  ]
}
