{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.3.0-dev.9facec7b2186/runtime-0.3.0-dev.9facec7b2186.module",
    "group": "uk.shusek.krwa",
    "module": "runtime",
    "version": "0.3.0-dev.9facec7b2186",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.9facec7b2186"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-wasm-js-0.3.0-dev.9facec7b2186.klib",
          "url": "runtime-wasm-js-0.3.0-dev.9facec7b2186.klib",
          "size": 364406,
          "sha512": "b189648140da53d4a8ab6d3e140616a82fa9d8ed5597dbeac3a3a1e07567acd1f9401a049495682616c0f33fd1feee1dc0eb09b02411c06d719ebbc326016529",
          "sha256": "c7be26ef6654602b1ff7f617cf890b4765af84a823913386d4594982c2c1696c",
          "sha1": "d27996806046418daf3d44594901a2b94556fcc3",
          "md5": "679c4da51cf7036d2ab1eb487d547d7e"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.9facec7b2186"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-wasm-js-0.3.0-dev.9facec7b2186.klib",
          "url": "runtime-wasm-js-0.3.0-dev.9facec7b2186.klib",
          "size": 364406,
          "sha512": "b189648140da53d4a8ab6d3e140616a82fa9d8ed5597dbeac3a3a1e07567acd1f9401a049495682616c0f33fd1feee1dc0eb09b02411c06d719ebbc326016529",
          "sha256": "c7be26ef6654602b1ff7f617cf890b4765af84a823913386d4594982c2c1696c",
          "sha1": "d27996806046418daf3d44594901a2b94556fcc3",
          "md5": "679c4da51cf7036d2ab1eb487d547d7e"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "runtime-wasm-js-0.3.0-dev.9facec7b2186-sources.jar",
          "url": "runtime-wasm-js-0.3.0-dev.9facec7b2186-sources.jar",
          "size": 72043,
          "sha512": "85ec2c87524214a5e1a0874cf4653160afa7a7eb545406988136f179648dae1180b3b7f8aaa00df0c712c87098ed5bbb99189c2f8814933af6ee52314931ad62",
          "sha256": "fb89d350c12c857431efb734993e14672bc66ec15b4b01682b176d80acc51eeb",
          "sha1": "90f7c1be55038beb03aa721e0ccd7588574ecb9f",
          "md5": "e1a5e13480d44f36719780161ff3ca6f"
        }
      ]
    }
  ]
}
