{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "runtime-wasmtime-android",
    "version": "0.3.0-dev.21b96b7a7348",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-wasmtime-android-metadata-0.3.0-dev.21b96b7a7348.jar",
          "url": "runtime-wasmtime-android-0.3.0-dev.21b96b7a7348.jar",
          "size": 648,
          "sha512": "fdc2e6615203db1f645b90952c7bfe11cb461a0af184cb62acbe46cd6b3c1ddc50a00f17894cef9e3b4d2ea9463a80082be1c9f3ce9bff9cab1fcdaa94e428cc",
          "sha256": "d12dd0b8c089f1200004d176563db524a613b6ce3216ae89925e7c6de62d42ef",
          "sha1": "8642b23bcb015c8e80a431bb041fdb4a0487a126",
          "md5": "bbaccdfc1a03723d0a9156e74e274aa0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-wasmtime-android-kotlin-0.3.0-dev.21b96b7a7348-sources.jar",
          "url": "runtime-wasmtime-android-0.3.0-dev.21b96b7a7348-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-wasmtime-android-android/0.3.0-dev.21b96b7a7348/runtime-wasmtime-android-android-0.3.0-dev.21b96b7a7348.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-wasmtime-android-android",
        "version": "0.3.0-dev.21b96b7a7348"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-wasmtime-android-android/0.3.0-dev.21b96b7a7348/runtime-wasmtime-android-android-0.3.0-dev.21b96b7a7348.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-wasmtime-android-android",
        "version": "0.3.0-dev.21b96b7a7348"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-wasmtime-android-android/0.3.0-dev.21b96b7a7348/runtime-wasmtime-android-android-0.3.0-dev.21b96b7a7348.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-wasmtime-android-android",
        "version": "0.3.0-dev.21b96b7a7348"
      }
    }
  ]
}
