{
  "formatVersion": "1.1",
  "component": {
    "url": "../../component-model/0.3.0-dev.21b96b7a7348/component-model-0.3.0-dev.21b96b7a7348.module",
    "group": "uk.shusek.krwa",
    "module": "component-model",
    "version": "0.3.0-dev.21b96b7a7348",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.21b96b7a7348"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.21b96b7a7348"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.21b96b7a7348"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-iosArm64Main-0.3.0-dev.21b96b7a7348.klib",
          "url": "component-model-iosarm64-0.3.0-dev.21b96b7a7348.klib",
          "size": 909552,
          "sha512": "da042a4b6d6659677302d44c235c065919b4e6f210eec2803182fa066827144cbc3133a3df3bc8d05d83d8fbf7eea360896acd33af754425c5885f816cbc83d2",
          "sha256": "956ab9e451b470062966278a287f6d96588f662c2a80bbb87af566a4f5b301e3",
          "sha1": "e5a0214ec4a5f8f8b0b6c57c1d78a4af1d9ead5f",
          "md5": "02cbc6404803f72be435a20e69bfddd9"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "component-model-iosarm64-0.3.0-dev.21b96b7a7348-sources.jar",
          "url": "component-model-iosarm64-0.3.0-dev.21b96b7a7348-sources.jar",
          "size": 149363,
          "sha512": "bb7ab818aa1b9cd17b0871004d0acef58211ac7a551cb5637cf37dd06efb6fb407497dfd2b95a09375c8974a59e4ecbc718a6ab110ace7c2b152257639b0049a",
          "sha256": "254cc01f9cc071550b82f5703b08af0a27346df5e546204f76438b4ee0b93ec7",
          "sha1": "01b38ac8ad3a25321113eb12c4eba64b4fad3971",
          "md5": "aef815d20396682d25c700b1d26a7497"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.21b96b7a7348"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.21b96b7a7348"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.21b96b7a7348"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-iosarm64-0.3.0-dev.21b96b7a7348-metadata.jar",
          "url": "component-model-iosarm64-0.3.0-dev.21b96b7a7348-metadata.jar",
          "size": 8184,
          "sha512": "b6c41a6f3dfb7ccd8e3e00290b9705c1222e3145c32c94c5a66d406048a93b1d7214b42937dbdf78e459aa32b3f429c35430f759eb6befdc12af07dca88780b8",
          "sha256": "0d149226faa570dc158c04e717e0dc4ef0210a2be9cd9afd70690a218ff8a679",
          "sha1": "df5d0b0d497bbb0640e4af3f075d9134b56e636b",
          "md5": "5379d8d0da1ae9519e712d080204f002"
        }
      ]
    }
  ]
}
