{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "cli-experimental",
    "version": "0.3.0-dev.ec3430fca82c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.ec3430fca82c.jar",
          "url": "cli-experimental-0.3.0-dev.ec3430fca82c.jar",
          "size": 6885,
          "sha512": "1c08fc14fa26fffa8c1043e326a9c8b4b4f76047eb58b85b026b60068bd729285d3c3f92c01f220414b1da1fcb4f29af2893d2bf723e848345743a88a5446286",
          "sha256": "6dfa23c8636e6b9355bfe1692a2b47795f7f5219ffe6a3cf1bf598c96c76be87",
          "sha1": "567f3f2330cca7522f9a765c919b24754b8490ad",
          "md5": "e25dd70c999e85f9c8c68630e069c30d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-bom",
          "version": {
            "requires": "9.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.7"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.ec3430fca82c"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.ec3430fca82c"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.ec3430fca82c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.ec3430fca82c.jar",
          "url": "cli-experimental-0.3.0-dev.ec3430fca82c.jar",
          "size": 6885,
          "sha512": "1c08fc14fa26fffa8c1043e326a9c8b4b4f76047eb58b85b026b60068bd729285d3c3f92c01f220414b1da1fcb4f29af2893d2bf723e848345743a88a5446286",
          "sha256": "6dfa23c8636e6b9355bfe1692a2b47795f7f5219ffe6a3cf1bf598c96c76be87",
          "sha1": "567f3f2330cca7522f9a765c919b24754b8490ad",
          "md5": "e25dd70c999e85f9c8c68630e069c30d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.ec3430fca82c-sources.jar",
          "url": "cli-experimental-0.3.0-dev.ec3430fca82c-sources.jar",
          "size": 2878,
          "sha512": "6d4189016b270e420f04f2c42667cd583009ac4a0dc890005016cae18a96b952bd8dfaed3f429a2bffcef37f24702491a93f0dc9ff255114b0ea42d182b6654b",
          "sha256": "04099799312bd871727c7ba88ea62af49e4e2e176088550a01c588d43c07b9ce",
          "sha1": "482db7103be06bee1f086656c6255b80c0240e4c",
          "md5": "fb173b1a801348a44a760fbc6cc4fcb3"
        }
      ]
    }
  ]
}
