{
  "formatVersion": "1.1",
  "component": {
    "url": "../../component-model/0.3.0-dev.90cee2d2dbef/component-model-0.3.0-dev.90cee2d2dbef.module",
    "group": "uk.shusek.krwa",
    "module": "component-model",
    "version": "0.3.0-dev.90cee2d2dbef",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.90cee2d2dbef.jar",
          "url": "component-model-jvm-0.3.0-dev.90cee2d2dbef.jar",
          "size": 1640344,
          "sha512": "c568129fa3f4bdd09a1a5e4a55a5d69118780e45d8677237e0733a85e9db454310cc57fb5f261c9820f8cf171bfc0ed45105fb5d9f36b5763d3e5c245e86ab31",
          "sha256": "30ae69c42ca21b4e1f9315e8443fe7a558af30399c26b3facc6f5ea4cf74c8cd",
          "sha1": "925358aad1e4a830eb9bc3c9eef39ffbfa7af118",
          "md5": "ff664528d53f930e7e9a23ecc6631348"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "log",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.90cee2d2dbef.jar",
          "url": "component-model-jvm-0.3.0-dev.90cee2d2dbef.jar",
          "size": 1640344,
          "sha512": "c568129fa3f4bdd09a1a5e4a55a5d69118780e45d8677237e0733a85e9db454310cc57fb5f261c9820f8cf171bfc0ed45105fb5d9f36b5763d3e5c245e86ab31",
          "sha256": "30ae69c42ca21b4e1f9315e8443fe7a558af30399c26b3facc6f5ea4cf74c8cd",
          "sha1": "925358aad1e4a830eb9bc3c9eef39ffbfa7af118",
          "md5": "ff664528d53f930e7e9a23ecc6631348"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "component-model-jvm-0.3.0-dev.90cee2d2dbef-sources.jar",
          "url": "component-model-jvm-0.3.0-dev.90cee2d2dbef-sources.jar",
          "size": 196282,
          "sha512": "34791233ebdbce8be85692a18ae02a9466eff07915dc9a7cd1bb3c7cf2f3b2c765df2cacc7804fa2634ca621fcb9c7a5fa1569979c1503d549cfe2ccab49d41f",
          "sha256": "7123ec2bfd32a25fde12d7b9ab34223112fe28d79b5085368a0ad8bbbaad7326",
          "sha1": "57ea3d13e7840b029d0e9a1ad2e1b85b2e2b2eb3",
          "md5": "37ca833beb2b9cc56dee4f6f05349081"
        }
      ]
    }
  ]
}
