{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "cli-experimental",
    "version": "0.3.0-dev.428bfc8e397e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.428bfc8e397e.jar",
          "url": "cli-experimental-0.3.0-dev.428bfc8e397e.jar",
          "size": 6885,
          "sha512": "f17bcf1a826236257bcd6d1cca811b2a1d2045e9f98f9d9bf4da8462a3428a045b9f97b58c563376175641f352e4d1d0c527ad5615bc80de6dcf13be0d4e3ca3",
          "sha256": "3a9ca70ebc507488c8915fd66f4a7863ce6820615c7af6a267bb92e3b32109e5",
          "sha1": "cac7e76f25f4b00503e52c58ac51fb10fa979b28",
          "md5": "289256c3f93d4391362cb7b8fbf9e79c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-bom",
          "version": {
            "requires": "9.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.7"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.428bfc8e397e.jar",
          "url": "cli-experimental-0.3.0-dev.428bfc8e397e.jar",
          "size": 6885,
          "sha512": "f17bcf1a826236257bcd6d1cca811b2a1d2045e9f98f9d9bf4da8462a3428a045b9f97b58c563376175641f352e4d1d0c527ad5615bc80de6dcf13be0d4e3ca3",
          "sha256": "3a9ca70ebc507488c8915fd66f4a7863ce6820615c7af6a267bb92e3b32109e5",
          "sha1": "cac7e76f25f4b00503e52c58ac51fb10fa979b28",
          "md5": "289256c3f93d4391362cb7b8fbf9e79c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.428bfc8e397e-sources.jar",
          "url": "cli-experimental-0.3.0-dev.428bfc8e397e-sources.jar",
          "size": 2878,
          "sha512": "09688fa1e0dc1c4787f8340d0febb08cafaa9eee2a6eec2ccaaf65e65ef9623efb381cc1d0ede03ae7594c7c6d02acb454b96e356bcbe3ef41feb6228c8f5df9",
          "sha256": "642fac0679e2278eec0bcb1ab9e714b1d875ef8b8896c42353f138f58a15ec72",
          "sha1": "def7d1dece020e8a4e288ad3dba16394747d7d1c",
          "md5": "5771eeb56b1bda6295fe4ea461caaaa6"
        }
      ]
    }
  ]
}
