{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasi-preview3/0.3.0-dev.a852e327fbb9/wasi-preview3-0.3.0-dev.a852e327fbb9.module",
    "group": "uk.shusek.krwa",
    "module": "wasi-preview3",
    "version": "0.3.0-dev.a852e327fbb9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-iosArm64Main-0.3.0-dev.a852e327fbb9.klib",
          "url": "wasi-preview3-iosarm64-0.3.0-dev.a852e327fbb9.klib",
          "size": 53367,
          "sha512": "743a484d6fdf7f4874324cc118fcee1352ddaaf32c9ef31c34fd97dd7434f5f660c018e0e47b29599a9c9032cc0c873cd61a968c99377c529656aa9bea79a9e1",
          "sha256": "7aca5688a7a198c7cbe3b460af399e5b60b5ef8534d26cd405e468e46d947cd9",
          "sha1": "af09ff0a9fc43590ae349ecbbfdbf3a013eed19d",
          "md5": "3e41983486d9e0228514252d006b7958"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "wasi-preview3-iosarm64-0.3.0-dev.a852e327fbb9-sources.jar",
          "url": "wasi-preview3-iosarm64-0.3.0-dev.a852e327fbb9-sources.jar",
          "size": 10746,
          "sha512": "c38b251e32dc5c07f29198ffe0ab1ca5dbeba29b30a272ae62813f24ea608175c7fc716c5a038a0dbb361b693136095b7ff6c776149800ec0a718020fbd46c5e",
          "sha256": "bee1d80357c051ea6df38467a627ea445985249edb96d1c0af8c7ca808115171",
          "sha1": "4deb292058bec3508cbf97c4e3b3f5b9c1441b71",
          "md5": "1dc4aef3152ef0d06357374d370a5383"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-iosarm64-0.3.0-dev.a852e327fbb9-metadata.jar",
          "url": "wasi-preview3-iosarm64-0.3.0-dev.a852e327fbb9-metadata.jar",
          "size": 4530,
          "sha512": "8f0bba011a56e9b6313c8997e6949b67c8260acd4a118900d71f054a527fab80f171bcffb754eba5b331e0014ec973e1c397ef5bfc6f12095dedf5fef8ee7eb6",
          "sha256": "a8a43f1f534fc9cc34fd8121663f684b4f571a90c1ea53af1dce03f812976883",
          "sha1": "c991bb31f888cb5d977a7b784d5daef233923f56",
          "md5": "f001c0bac95a7221919d42cfaa780fb4"
        }
      ]
    }
  ]
}
