{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "runtime",
    "version": "0.3.0-dev.ce74cc1b5a6f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.ce74cc1b5a6f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-metadata-0.3.0-dev.ce74cc1b5a6f.jar",
          "url": "runtime-0.3.0-dev.ce74cc1b5a6f.jar",
          "size": 42286,
          "sha512": "bae3f0a737a920445b58a8dc214dd78f58ffacdd1498ec4edce8611ce7a1a5e9b0d226781d9688c1980792b85468d7cd46b5ff81316278c7975b7ca9b58a06d9",
          "sha256": "ff627ee205dda550a26de1412a7e680ff48ac2770d65c8aeea28f9e57689ca5d",
          "sha1": "665cf6a4b3d8b9da5a8096c3c6ba1d85a2bfac33",
          "md5": "787749c702398dbb34e8dda329a0e61e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-kotlin-0.3.0-dev.ce74cc1b5a6f-sources.jar",
          "url": "runtime-0.3.0-dev.ce74cc1b5a6f-sources.jar",
          "size": 67538,
          "sha512": "3a811ed83bf58a861f0b3761f917ee79541cb9a3f5f8d2eadedbcb852e0365db627702dfa559d1b60fb2f06a7f7bc56f47b8bed5688c8ac1bd56be5946e67126",
          "sha256": "6d779e7ba9f30d16e1c642a4867ac8f9ca6b3cad2cf69c0e11f9eeeff70f200c",
          "sha1": "e7bbebbc971ecf5dc818ee68de37b017ff7ad80a",
          "md5": "bd1a89bb0476aa6b63bd4cc743173165"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.3.0-dev.ce74cc1b5a6f/runtime-iosarm64-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iosarm64",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.3.0-dev.ce74cc1b5a6f/runtime-iosarm64-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iosarm64",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.3.0-dev.ce74cc1b5a6f/runtime-iosarm64-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iosarm64",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.3.0-dev.ce74cc1b5a6f/runtime-iossimulatorarm64-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iossimulatorarm64",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.3.0-dev.ce74cc1b5a6f/runtime-iossimulatorarm64-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iossimulatorarm64",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.3.0-dev.ce74cc1b5a6f/runtime-iossimulatorarm64-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iossimulatorarm64",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.3.0-dev.ce74cc1b5a6f/runtime-jvm-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-jvm",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.3.0-dev.ce74cc1b5a6f/runtime-jvm-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-jvm",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.3.0-dev.ce74cc1b5a6f/runtime-jvm-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-jvm",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../runtime-wasm-js/0.3.0-dev.ce74cc1b5a6f/runtime-wasm-js-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-wasm-js",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../runtime-wasm-js/0.3.0-dev.ce74cc1b5a6f/runtime-wasm-js-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-wasm-js",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../runtime-wasm-js/0.3.0-dev.ce74cc1b5a6f/runtime-wasm-js-0.3.0-dev.ce74cc1b5a6f.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-wasm-js",
        "version": "0.3.0-dev.ce74cc1b5a6f"
      }
    }
  ]
}
