{
  "formatVersion": "1.1",
  "component": {
    "url": "../../component-model/0.3.0-dev.428bfc8e397e/component-model-0.3.0-dev.428bfc8e397e.module",
    "group": "uk.shusek.krwa",
    "module": "component-model",
    "version": "0.3.0-dev.428bfc8e397e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-wasm-js-0.3.0-dev.428bfc8e397e.klib",
          "url": "component-model-wasm-js-0.3.0-dev.428bfc8e397e.klib",
          "size": 915371,
          "sha512": "fcd37ebbbc32813e3c6912cf1d2ffce5a16acb2d6d7e1207b3eb2de992683a2d5557244c500c0fe73e60d8b7fac06453ac01517cd47dabf73bc11071bea09023",
          "sha256": "7a25bec65636614593eb21a360844f6b70472307eb7e1e5fdaf97b932559de90",
          "sha1": "27d83df58777626b94a12baf480cf3bd8b721348",
          "md5": "06facc21456bad9d1fd07330e08863ca"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-wasm-js-0.3.0-dev.428bfc8e397e.klib",
          "url": "component-model-wasm-js-0.3.0-dev.428bfc8e397e.klib",
          "size": 915371,
          "sha512": "fcd37ebbbc32813e3c6912cf1d2ffce5a16acb2d6d7e1207b3eb2de992683a2d5557244c500c0fe73e60d8b7fac06453ac01517cd47dabf73bc11071bea09023",
          "sha256": "7a25bec65636614593eb21a360844f6b70472307eb7e1e5fdaf97b932559de90",
          "sha1": "27d83df58777626b94a12baf480cf3bd8b721348",
          "md5": "06facc21456bad9d1fd07330e08863ca"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "component-model-wasm-js-0.3.0-dev.428bfc8e397e-sources.jar",
          "url": "component-model-wasm-js-0.3.0-dev.428bfc8e397e-sources.jar",
          "size": 151413,
          "sha512": "3ae4972aee81a13a206dcaaccc2863a4e1e2f338a1ae7eaea6edc64342f3d09bf52f089006b56a0d0ca441393c11afdb49c0325af1a0190784940baa842e8d13",
          "sha256": "be05b0d2fc0f1626720e737d8b70f13d2d6e19eb611426bd47110ba03c3f98e7",
          "sha1": "62b5f0bbe943ada9afaca844a8e877c52be755b2",
          "md5": "d02caf3ed534747f19e65a04b51f3b86"
        }
      ]
    }
  ]
}
