{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotations/0.3.0-dev.59c0bdcaad2a/annotations-0.3.0-dev.59c0bdcaad2a.module",
    "group": "uk.shusek.krwa",
    "module": "annotations",
    "version": "0.3.0-dev.59c0bdcaad2a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-wasm-js-0.3.0-dev.59c0bdcaad2a.klib",
          "url": "annotations-wasm-js-0.3.0-dev.59c0bdcaad2a.klib",
          "size": 8130,
          "sha512": "0044a82435287dbb80d63b9e234388273576bf4cbe582c8c7a29633dc18a2e9c70d086f221d7aacfe6b89a14eb6716d1617aeeaf3bbfbb84431e6b4675753601",
          "sha256": "b3bd9dd344708ccbba71e021bde59399de10b36657b12ca69291a8b35452b9ca",
          "sha1": "50a839f7bacc96ca46593d2cff9a1a63de588a9a",
          "md5": "fc052f982c81d963c7a47b7405e52e6e"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-wasm-js-0.3.0-dev.59c0bdcaad2a.klib",
          "url": "annotations-wasm-js-0.3.0-dev.59c0bdcaad2a.klib",
          "size": 8130,
          "sha512": "0044a82435287dbb80d63b9e234388273576bf4cbe582c8c7a29633dc18a2e9c70d086f221d7aacfe6b89a14eb6716d1617aeeaf3bbfbb84431e6b4675753601",
          "sha256": "b3bd9dd344708ccbba71e021bde59399de10b36657b12ca69291a8b35452b9ca",
          "sha1": "50a839f7bacc96ca46593d2cff9a1a63de588a9a",
          "md5": "fc052f982c81d963c7a47b7405e52e6e"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "annotations-wasm-js-0.3.0-dev.59c0bdcaad2a-sources.jar",
          "url": "annotations-wasm-js-0.3.0-dev.59c0bdcaad2a-sources.jar",
          "size": 2453,
          "sha512": "6d6f4aae2d93a926473bb47df523a8ce41a65da675f99eed5717ce20998b4ae4120488186444b603439cb94260705446ee2dff5528962db6eec5a1e5120eaa6e",
          "sha256": "ed5d93d4836238ffaff5db35a28a36a7df393f5528810c443e4a9c0a1e0250a6",
          "sha1": "f3645b27317c7a20ffc7941724fb24f9a2d38585",
          "md5": "1bae3d7db028bd3fb5d8c41dd8c4b1b3"
        }
      ]
    }
  ]
}
