{
  "formatVersion": "1.1",
  "component": {
    "url": "../../component-model/0.3.0-dev.8347044dd14e/component-model-0.3.0-dev.8347044dd14e.module",
    "group": "uk.shusek.krwa",
    "module": "component-model",
    "version": "0.3.0-dev.8347044dd14e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-wasm-js-0.3.0-dev.8347044dd14e.klib",
          "url": "component-model-wasm-js-0.3.0-dev.8347044dd14e.klib",
          "size": 917565,
          "sha512": "d2440d269e7c0f2cedeff04af6e658949b264c41a78bd114b1774869836ae8a0aef673571ce7543a80473314f5c20259b70b84c99fb30a58413116d46502d51b",
          "sha256": "7996e7cef146486db303f40dcbc8efeccef591fabf6221f592d81c6325957903",
          "sha1": "d48b7125f1349b765a0ff124dadf58b9010288cc",
          "md5": "653cb8cfff535810d7b3868631c1fb27"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.8347044dd14e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-wasm-js-0.3.0-dev.8347044dd14e.klib",
          "url": "component-model-wasm-js-0.3.0-dev.8347044dd14e.klib",
          "size": 917565,
          "sha512": "d2440d269e7c0f2cedeff04af6e658949b264c41a78bd114b1774869836ae8a0aef673571ce7543a80473314f5c20259b70b84c99fb30a58413116d46502d51b",
          "sha256": "7996e7cef146486db303f40dcbc8efeccef591fabf6221f592d81c6325957903",
          "sha1": "d48b7125f1349b765a0ff124dadf58b9010288cc",
          "md5": "653cb8cfff535810d7b3868631c1fb27"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "component-model-wasm-js-0.3.0-dev.8347044dd14e-sources.jar",
          "url": "component-model-wasm-js-0.3.0-dev.8347044dd14e-sources.jar",
          "size": 151803,
          "sha512": "42a356bfc5504202b6a4e4c425e2fefabed6aa7d6261c3ef4b444c7c2808ef228ee4be53a50ae0ff61d7e91d380a8f4a10d6397e4f766d3f6a00a956e888a15f",
          "sha256": "3df28899780680499de23c3304581447e55a383505cfd8f6bf8f80daa2f20bff",
          "sha1": "0e5aa8f1096ec6abbca2d0e36f6ef4673239b219",
          "md5": "72f10c79b641662f78249287c473620e"
        }
      ]
    }
  ]
}
