{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "runtime",
    "version": "0.3.0-dev.ec3430fca82c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.ec3430fca82c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-metadata-0.3.0-dev.ec3430fca82c.jar",
          "url": "runtime-0.3.0-dev.ec3430fca82c.jar",
          "size": 42249,
          "sha512": "24c40fab59ce5597c3d7f7e20a263ee97ebae8453efec4b7ef01138f9c99cb91d65ea95c0e044f1c23ca9cb38bf20be9f0050af65be7712e6249ce62513f976f",
          "sha256": "240501c9585dfc5fb1d64e66d05cf7e6f5b84292151bf2df67e22180455d0a34",
          "sha1": "a16d9c595f23d4970ddd2f5964f6e3a4a6e4abbc",
          "md5": "8babf84f49ca1d240769a99aa4757b08"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-kotlin-0.3.0-dev.ec3430fca82c-sources.jar",
          "url": "runtime-0.3.0-dev.ec3430fca82c-sources.jar",
          "size": 67142,
          "sha512": "b53c46bebcadf2a31608c21e94b6ac4db9ca2281148b8bc96312f3e79599de89afdff09ea9ac2e5403db43c6aea1bbf0aabbe302583408b79176e4412a523618",
          "sha256": "7feef4a1f6010ec3e888e62dd659650014f28786f9fded7a7494d0e031eb6e2f",
          "sha1": "798d30980e4ad7f09291a400786bd287146e2b49",
          "md5": "4f66789b28b1d4639e4f1df7dc63a9bc"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.3.0-dev.ec3430fca82c/runtime-iosarm64-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iosarm64",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.3.0-dev.ec3430fca82c/runtime-iosarm64-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iosarm64",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/0.3.0-dev.ec3430fca82c/runtime-iosarm64-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iosarm64",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.3.0-dev.ec3430fca82c/runtime-iossimulatorarm64-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iossimulatorarm64",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.3.0-dev.ec3430fca82c/runtime-iossimulatorarm64-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iossimulatorarm64",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/0.3.0-dev.ec3430fca82c/runtime-iossimulatorarm64-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-iossimulatorarm64",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.3.0-dev.ec3430fca82c/runtime-jvm-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-jvm",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.3.0-dev.ec3430fca82c/runtime-jvm-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-jvm",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-jvm/0.3.0-dev.ec3430fca82c/runtime-jvm-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-jvm",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../runtime-wasm-js/0.3.0-dev.ec3430fca82c/runtime-wasm-js-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-wasm-js",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../runtime-wasm-js/0.3.0-dev.ec3430fca82c/runtime-wasm-js-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-wasm-js",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../runtime-wasm-js/0.3.0-dev.ec3430fca82c/runtime-wasm-js-0.3.0-dev.ec3430fca82c.module",
        "group": "uk.shusek.krwa",
        "module": "runtime-wasm-js",
        "version": "0.3.0-dev.ec3430fca82c"
      }
    }
  ]
}
