{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-wasmtime-android/0.3.0-dev.90cee2d2dbef/runtime-wasmtime-android-0.3.0-dev.90cee2d2dbef.module",
    "group": "uk.shusek.krwa",
    "module": "runtime-wasmtime-android",
    "version": "0.3.0-dev.90cee2d2dbef",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-wasmtime-android.aar",
          "url": "runtime-wasmtime-android-android-0.3.0-dev.90cee2d2dbef.aar",
          "size": 26925891,
          "sha512": "2acd976055888dac066dd7ee8254d6d36b7f449616006a4f9a9bb578511dc601e39cabd875e6a0add4ae47858a293a2dae058d7f0439954c2db7f164dfb7def0",
          "sha256": "ab93b041a28fa17baaa7c4e5c9ea9c6daa37dce449d768b5e92d876de48b0a40",
          "sha1": "157122117afa1b8fd74bf8fc32c2ea06d163a3fa",
          "md5": "ecaa633f0092e7929a09f28e65aeb317"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.90cee2d2dbef"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-wasmtime-android.aar",
          "url": "runtime-wasmtime-android-android-0.3.0-dev.90cee2d2dbef.aar",
          "size": 26925891,
          "sha512": "2acd976055888dac066dd7ee8254d6d36b7f449616006a4f9a9bb578511dc601e39cabd875e6a0add4ae47858a293a2dae058d7f0439954c2db7f164dfb7def0",
          "sha256": "ab93b041a28fa17baaa7c4e5c9ea9c6daa37dce449d768b5e92d876de48b0a40",
          "sha1": "157122117afa1b8fd74bf8fc32c2ea06d163a3fa",
          "md5": "ecaa633f0092e7929a09f28e65aeb317"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "runtime-wasmtime-android-android-0.3.0-dev.90cee2d2dbef-sources.jar",
          "url": "runtime-wasmtime-android-android-0.3.0-dev.90cee2d2dbef-sources.jar",
          "size": 12356,
          "sha512": "b3d94fe691b84c5360bcb1b85f3a5a9aa082d7b54bbc7755ce70c2d5bcd4f10fc51398ad6c7374aaaaa3f95cabfa03a14810b15ee9909de721b4b1f423849396",
          "sha256": "f360ab6df96780d43c5a4a05130ae63baad733d0132c28c6914c4fa4c77f6d8f",
          "sha1": "55794cce1ed7bb4fe2c560e0aa14402bcfd03a46",
          "md5": "43ba67c48bef4bc7ba03e0bdc63b7642"
        }
      ]
    }
  ]
}
