{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.3.0-dev.f3c34df3a402/runtime-0.3.0-dev.f3c34df3a402.module",
    "group": "uk.shusek.krwa",
    "module": "runtime",
    "version": "0.3.0-dev.f3c34df3a402",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.f3c34df3a402"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iosSimulatorArm64Main-0.3.0-dev.f3c34df3a402.klib",
          "url": "runtime-iossimulatorarm64-0.3.0-dev.f3c34df3a402.klib",
          "size": 347735,
          "sha512": "2db7fa13dfef1f205a45455d18cfc4fd52df2201d145a9ed08d26f558ef1ec0d64ab146bfb0f8d6f06a6d983751e0ed9fef7945125d8a4aeb3f1caf9bb386317",
          "sha256": "d200bc023ed818f1cecad191190d4d739bb1dbfb82a816e751c3aa545ad4d367",
          "sha1": "8b16d1f8c5d0c67018b7fb411f02dc56266e6588",
          "md5": "81307e5534bda52631d3a90333138ead"
        },
        {
          "name": "runtime-iosSimulatorArm64Cinterop-wasmtimePulleyMain-0.3.0-dev.f3c34df3a402.klib",
          "url": "runtime-iossimulatorarm64-0.3.0-dev.f3c34df3a402-cinterop-wasmtimePulley.klib",
          "size": 41031833,
          "sha512": "03cf4c4d959732f498c9099ed00901bf06c67c065ef1483d7b75555f4086161262defc9df84157c1c93a6aaae75377f43fc9fbed793bf79e5e0284fdb4f2376d",
          "sha256": "1443c6651a77a86d8d8df5a8ae910baa1900baaaed9af8a4abad4d10f6832b69",
          "sha1": "34fc6d38acedba762993ba2024a722257970d54c",
          "md5": "86b88f780c93ff6eab7d4ab5b7934732"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.3.0-dev.f3c34df3a402-sources.jar",
          "url": "runtime-iossimulatorarm64-0.3.0-dev.f3c34df3a402-sources.jar",
          "size": 67538,
          "sha512": "c4e334b2e4e7f2fa3ae2722f5e65de006f1ae14c15d0916038e28030ef955dd5725fc4c3c30dd5b930857c30af167a1e0f6028719c0579cfc31ab70c8e96271a",
          "sha256": "c262b7a94913db08d09c49a91378de25560ab6c6ee792eff83a168dc4f7b49cf",
          "sha1": "3c2d9661b4c67271247a1b98a5c90428c13e740e",
          "md5": "d274dd941f675291e05342abf6bafbfa"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.f3c34df3a402"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-iossimulatorarm64-0.3.0-dev.f3c34df3a402-metadata.jar",
          "url": "runtime-iossimulatorarm64-0.3.0-dev.f3c34df3a402-metadata.jar",
          "size": 34443,
          "sha512": "d05d5d88dc3e22d188893bd94e85e0d0d28fb6417d635cdbdfd59f4011e9a9f890d3de12efa3ed411e3d983926524cf42f1cf741d8548b864a4a8a2c1bdafe47",
          "sha256": "36f34eb5f5de72f358e6261982946f8783df98535637a4ed1da97b0bbbc473ae",
          "sha1": "329592d2776f921e8877f7ec4013aa6bcb5611f3",
          "md5": "83dda7653201846eca3acc933af7b434"
        }
      ]
    }
  ]
}
