{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-wasmtime-android/0.3.0-dev.f3c34df3a402/runtime-wasmtime-android-0.3.0-dev.f3c34df3a402.module",
    "group": "uk.shusek.krwa",
    "module": "runtime-wasmtime-android",
    "version": "0.3.0-dev.f3c34df3a402",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.f3c34df3a402"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-wasmtime-android.aar",
          "url": "runtime-wasmtime-android-android-0.3.0-dev.f3c34df3a402.aar",
          "size": 26900993,
          "sha512": "541a3e4e5ab3d38c680b0ab89a3cd46906c1f427765626d1287b80b68ac1a10ea0d90df9d3bae301afd67974a4f1a8515bd1c50f39dde70a2df9bd08422e9a52",
          "sha256": "d63fecdd66757d30eefd30d3f934b1219e33220c147d0297d389f105bd13dd58",
          "sha1": "9ce5ed97865c5b331e7f99ae64018254bc6055f7",
          "md5": "37b311746711362a4cdbb2de93fdc53a"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.f3c34df3a402"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-wasmtime-android.aar",
          "url": "runtime-wasmtime-android-android-0.3.0-dev.f3c34df3a402.aar",
          "size": 26900993,
          "sha512": "541a3e4e5ab3d38c680b0ab89a3cd46906c1f427765626d1287b80b68ac1a10ea0d90df9d3bae301afd67974a4f1a8515bd1c50f39dde70a2df9bd08422e9a52",
          "sha256": "d63fecdd66757d30eefd30d3f934b1219e33220c147d0297d389f105bd13dd58",
          "sha1": "9ce5ed97865c5b331e7f99ae64018254bc6055f7",
          "md5": "37b311746711362a4cdbb2de93fdc53a"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "runtime-wasmtime-android-android-0.3.0-dev.f3c34df3a402-sources.jar",
          "url": "runtime-wasmtime-android-android-0.3.0-dev.f3c34df3a402-sources.jar",
          "size": 12356,
          "sha512": "b3d94fe691b84c5360bcb1b85f3a5a9aa082d7b54bbc7755ce70c2d5bcd4f10fc51398ad6c7374aaaaa3f95cabfa03a14810b15ee9909de721b4b1f423849396",
          "sha256": "f360ab6df96780d43c5a4a05130ae63baad733d0132c28c6914c4fa4c77f6d8f",
          "sha1": "55794cce1ed7bb4fe2c560e0aa14402bcfd03a46",
          "md5": "43ba67c48bef4bc7ba03e0bdc63b7642"
        }
      ]
    }
  ]
}
