{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/0.3.0-dev.a852e327fbb9/runtime-0.3.0-dev.a852e327fbb9.module",
    "group": "uk.shusek.krwa",
    "module": "runtime",
    "version": "0.3.0-dev.a852e327fbb9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-jvm-0.3.0-dev.a852e327fbb9.jar",
          "url": "runtime-jvm-0.3.0-dev.a852e327fbb9.jar",
          "size": 362769,
          "sha512": "0521bd3833c0d94daa6b63fe39afb9404188be7f98acd790aefa05e446fd6d6aa1e91837dd6297df0712496ee781e1e55dd63df3f3aee2301fa76d3844df5789",
          "sha256": "61c53fa016b764962f1549bc49e957453e9ddebc30d197ca87f57ce7585e9da4",
          "sha1": "e3526f61c88b7475de17be39326ef72eaad2ddad",
          "md5": "1488252b596571bf40529167347e1d2c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-jvm-0.3.0-dev.a852e327fbb9.jar",
          "url": "runtime-jvm-0.3.0-dev.a852e327fbb9.jar",
          "size": 362769,
          "sha512": "0521bd3833c0d94daa6b63fe39afb9404188be7f98acd790aefa05e446fd6d6aa1e91837dd6297df0712496ee781e1e55dd63df3f3aee2301fa76d3844df5789",
          "sha256": "61c53fa016b764962f1549bc49e957453e9ddebc30d197ca87f57ce7585e9da4",
          "sha1": "e3526f61c88b7475de17be39326ef72eaad2ddad",
          "md5": "1488252b596571bf40529167347e1d2c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "runtime-jvm-0.3.0-dev.a852e327fbb9-sources.jar",
          "url": "runtime-jvm-0.3.0-dev.a852e327fbb9-sources.jar",
          "size": 93231,
          "sha512": "12526a799bae4a700dc234bb35508d84508540f8a99b29566b1b10b8d286d26e1b509d08230a7281af47d3896f5cfa2a13d45f4e6ac96b45c805414300ccb567",
          "sha256": "bb0618ebec59bbca5a8ee1ec982e576df6e1f57c566fc47e1c0c31a74ecd2e3e",
          "sha1": "0491cb3bb43bd7bd83743caf8162146e556740ee",
          "md5": "03b9e1988bf5ac16db0fc638632d5a93"
        }
      ]
    }
  ]
}
