{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "cli-experimental",
    "version": "0.3.0-dev.a852e327fbb9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.a852e327fbb9.jar",
          "url": "cli-experimental-0.3.0-dev.a852e327fbb9.jar",
          "size": 6885,
          "sha512": "f63260e874e0fa7d26ebdbd13ac0bc6e19646ad8e0ab3c8272d36e3d4429e4073f638ca65d827adb5acedf8ba042247afec8ef83d40cb6a8d3b6787723062ef3",
          "sha256": "5553a4546068211b11395cc09951d45c1abc829ce502f000b00d9391cb1478ce",
          "sha1": "a7c7a25fd005c1fd027cd22396c0a7ed415e6532",
          "md5": "997c31164a749c3eb840f49a5518418d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-bom",
          "version": {
            "requires": "9.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.7"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.a852e327fbb9.jar",
          "url": "cli-experimental-0.3.0-dev.a852e327fbb9.jar",
          "size": 6885,
          "sha512": "f63260e874e0fa7d26ebdbd13ac0bc6e19646ad8e0ab3c8272d36e3d4429e4073f638ca65d827adb5acedf8ba042247afec8ef83d40cb6a8d3b6787723062ef3",
          "sha256": "5553a4546068211b11395cc09951d45c1abc829ce502f000b00d9391cb1478ce",
          "sha1": "a7c7a25fd005c1fd027cd22396c0a7ed415e6532",
          "md5": "997c31164a749c3eb840f49a5518418d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cli-experimental-0.3.0-dev.a852e327fbb9-sources.jar",
          "url": "cli-experimental-0.3.0-dev.a852e327fbb9-sources.jar",
          "size": 2878,
          "sha512": "9a357bc9ca2ea3746fc718d9eaa7673a8ade8dcbded7c4e4148153ef14fb827966e6c963793836529738eae772160039a9360325359e74a18c97c00d14cfb9ce",
          "sha256": "1ce8e72f53f017a67d4093031a41334981c697f2234b8df2bdc7d616d31c4da6",
          "sha1": "1bc85df286ea8f80e2c85c19ec7a01aa88459a77",
          "md5": "fc068ae97df6d5d720aca5dc2cef61dd"
        }
      ]
    }
  ]
}
