{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "component-model-gradle-plugin",
    "version": "0.3.0-dev.428bfc8e397e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-gradle-plugin-0.3.0-dev.428bfc8e397e.jar",
          "url": "component-model-gradle-plugin-0.3.0-dev.428bfc8e397e.jar",
          "size": 73529,
          "sha512": "1d1afbfd4c50a5cfe192c26310eb13ddc81c3d1c993cf53ddc0f7472969faf004e551381b4c19aa20ec906ad8e3100a0fb1fa6625fe7087f20dac1c7b17909cd",
          "sha256": "d9688aa8d3dfa64ffc51436c2100d8ead7a83ecdeb04039a5f68799310fc169a",
          "sha1": "6a4e418ae1e0ba7289a1483afd57123124aea0f2",
          "md5": "86dc54f9a117805af18ca1907ef3e8a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "component-model-tooling",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-gradle-plugin-0.3.0-dev.428bfc8e397e.jar",
          "url": "component-model-gradle-plugin-0.3.0-dev.428bfc8e397e.jar",
          "size": 73529,
          "sha512": "1d1afbfd4c50a5cfe192c26310eb13ddc81c3d1c993cf53ddc0f7472969faf004e551381b4c19aa20ec906ad8e3100a0fb1fa6625fe7087f20dac1c7b17909cd",
          "sha256": "d9688aa8d3dfa64ffc51436c2100d8ead7a83ecdeb04039a5f68799310fc169a",
          "sha1": "6a4e418ae1e0ba7289a1483afd57123124aea0f2",
          "md5": "86dc54f9a117805af18ca1907ef3e8a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "component-model-gradle-plugin-0.3.0-dev.428bfc8e397e-sources.jar",
          "url": "component-model-gradle-plugin-0.3.0-dev.428bfc8e397e-sources.jar",
          "size": 10479,
          "sha512": "f97ac66368798baee285385a468b4cef0963731f301426ce67b54cb8437584e191f1114936d49d4c140efb30295cd73bb118f9806696fc543b37880b747e046a",
          "sha256": "d062a9f5543708945155482ed10228255cb996921468859f480fe27e682081a2",
          "sha1": "e6defdec9ae1105eeb1b07d9a0bc62577d3a88d4",
          "md5": "a7f5b1371d0a09da16f919dde27e1bce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "component-model-gradle-plugin-0.3.0-dev.428bfc8e397e-javadoc.jar",
          "url": "component-model-gradle-plugin-0.3.0-dev.428bfc8e397e-javadoc.jar",
          "size": 1033,
          "sha512": "c0ba2edb9f7832739c8c64c1e8ce07985195e8052af9919a6bd6fbdde1aef33236fe9b2095c301d0d09d675ec77b5cb8afdcbef3fb803791c251d4728569c2a8",
          "sha256": "25faf27a63c0ce3a6ad3e900a7c933066ab502e4caf3459a01903538fc728534",
          "sha1": "1be9ff0cef099cc3b82131fdc3d5ee963fe39486",
          "md5": "01f42b2fc1e614e18001925fdb142ce8"
        }
      ]
    }
  ]
}
