{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasi-preview3/0.3.0-dev.e3ca3a2569a9/wasi-preview3-0.3.0-dev.e3ca3a2569a9.module",
    "group": "uk.shusek.krwa",
    "module": "wasi-preview3",
    "version": "0.3.0-dev.e3ca3a2569a9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-jvm-0.3.0-dev.e3ca3a2569a9.jar",
          "url": "wasi-preview3-jvm-0.3.0-dev.e3ca3a2569a9.jar",
          "size": 77961,
          "sha512": "11c143234006ad51cb449fc03e37b745932e823921b0ed6beb9b22bc257e8c3c6dc7fb9f84b7461d68bddbd189787a0bd9f4b202eb65b9813c893b0c7bfbc13f",
          "sha256": "65755287966cf6c34e665778570d1d8c067686b20c10996edcd97df5d680a59a",
          "sha1": "05c3493bc9d772c9bbfc8e84d32dc435aa5ec37e",
          "md5": "c387d09c5b34a4a17e49ba538c3df2e1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.e3ca3a2569a9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-jvm-0.3.0-dev.e3ca3a2569a9.jar",
          "url": "wasi-preview3-jvm-0.3.0-dev.e3ca3a2569a9.jar",
          "size": 77961,
          "sha512": "11c143234006ad51cb449fc03e37b745932e823921b0ed6beb9b22bc257e8c3c6dc7fb9f84b7461d68bddbd189787a0bd9f4b202eb65b9813c893b0c7bfbc13f",
          "sha256": "65755287966cf6c34e665778570d1d8c067686b20c10996edcd97df5d680a59a",
          "sha1": "05c3493bc9d772c9bbfc8e84d32dc435aa5ec37e",
          "md5": "c387d09c5b34a4a17e49ba538c3df2e1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "wasi-preview3-jvm-0.3.0-dev.e3ca3a2569a9-sources.jar",
          "url": "wasi-preview3-jvm-0.3.0-dev.e3ca3a2569a9-sources.jar",
          "size": 12512,
          "sha512": "a95b033cc622621a19010dd02e3eb99f448b8ced0c6b459660ee92d855c5488de6cd150849ce7ba347a997d01105c92a403326b064734cac17d38d02a6113a96",
          "sha256": "0d772ae40a296c39ff5eac1d8a5bd9766537aec73e4cb64859a8737a6e0ee4b8",
          "sha1": "b6b78fd6b6f2a3bf4b599498d2be0a8fc9a9c2c1",
          "md5": "1eef3d6fabc9a0b4c1da26644beb44d2"
        }
      ]
    }
  ]
}
