{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "wasm-tools",
    "version": "0.3.0-dev.428bfc8e397e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasm-tools-0.3.0-dev.428bfc8e397e.jar",
          "url": "wasm-tools-0.3.0-dev.428bfc8e397e.jar",
          "size": 3769723,
          "sha512": "91a8703518cab33747ac89c8278ecb78ac1ba70242a4b13a92350c89eeb6668278a79a4b554c77bf189ba97ee935509ba880119fecaadeb37b83f1f66e27ca46",
          "sha256": "f8e28f9f859316359a15058198995858c6da82311bb227a21a87ce71c4b73dcf",
          "sha1": "f0d6b7ce351ba4c249b74a65e9eb0235211dc38e",
          "md5": "456735b9ae371922fce106a76d37a3f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-bom",
          "version": {
            "requires": "9.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.roastedroot",
          "module": "zerofs",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "log",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasm-tools-0.3.0-dev.428bfc8e397e.jar",
          "url": "wasm-tools-0.3.0-dev.428bfc8e397e.jar",
          "size": 3769723,
          "sha512": "91a8703518cab33747ac89c8278ecb78ac1ba70242a4b13a92350c89eeb6668278a79a4b554c77bf189ba97ee935509ba880119fecaadeb37b83f1f66e27ca46",
          "sha256": "f8e28f9f859316359a15058198995858c6da82311bb227a21a87ce71c4b73dcf",
          "sha1": "f0d6b7ce351ba4c249b74a65e9eb0235211dc38e",
          "md5": "456735b9ae371922fce106a76d37a3f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wasm-tools-0.3.0-dev.428bfc8e397e-sources.jar",
          "url": "wasm-tools-0.3.0-dev.428bfc8e397e-sources.jar",
          "size": 3717514,
          "sha512": "246d9b7e2039097f31b7ef34a14be0f51fe4faff45bf325b8b3e606ab6f8b6d427e0ecb07751f6ccbcf35425db9e5e5c5408374684524ff7c93d943e632e782a",
          "sha256": "e79062f9bbc2097f1e713d5892a6df65f5e38777cc07c69e2e667c45cbe762eb",
          "sha1": "b73a7bb1e67b06fc381dac99b463e8dc8eb07aaa",
          "md5": "631699547be776cc6106a199b4337629"
        }
      ]
    }
  ]
}
