{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasm/0.3.0-dev.ce74cc1b5a6f/wasm-0.3.0-dev.ce74cc1b5a6f.module",
    "group": "uk.shusek.krwa",
    "module": "wasm",
    "version": "0.3.0-dev.ce74cc1b5a6f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasm-wasm-js-0.3.0-dev.ce74cc1b5a6f.klib",
          "url": "wasm-wasm-js-0.3.0-dev.ce74cc1b5a6f.klib",
          "size": 369539,
          "sha512": "8261f81f817d5bb5fce5a3ee03a83be2a91c8c244028aff09f671739f01de497538aa4f75a67d5ed3958226a6f7d0ce5d343c89ca1270569097897b920079528",
          "sha256": "5a245b1d343bfd116c7a0894385d9c7901234ff88a989e6a7409dca6562a2ae7",
          "sha1": "bff6c153f8d49e7c6310c7b5d61a01662b280a82",
          "md5": "922d8b931a76a3141ad25869c96b1b45"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "wasm-wasm-js-0.3.0-dev.ce74cc1b5a6f.klib",
          "url": "wasm-wasm-js-0.3.0-dev.ce74cc1b5a6f.klib",
          "size": 369539,
          "sha512": "8261f81f817d5bb5fce5a3ee03a83be2a91c8c244028aff09f671739f01de497538aa4f75a67d5ed3958226a6f7d0ce5d343c89ca1270569097897b920079528",
          "sha256": "5a245b1d343bfd116c7a0894385d9c7901234ff88a989e6a7409dca6562a2ae7",
          "sha1": "bff6c153f8d49e7c6310c7b5d61a01662b280a82",
          "md5": "922d8b931a76a3141ad25869c96b1b45"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "wasm-wasm-js-0.3.0-dev.ce74cc1b5a6f-sources.jar",
          "url": "wasm-wasm-js-0.3.0-dev.ce74cc1b5a6f-sources.jar",
          "size": 82801,
          "sha512": "6dac747f4973b7f99bf5e885caddeccd39e8784e16efaac44ad138d7d04529e9fd7c8078b2d918a1daac8fc053fc577e3c06437ba549e70da0b32a84a50fd5ad",
          "sha256": "1def46b6feb1621c8659a2a272e42d2249d73032b81d2eb9fb341fdaf0c6a536",
          "sha1": "bae5901421489bdc1f99e2168fc3050e3b19a454",
          "md5": "9a6f81b8ab5973a09e97d73eab7dbe01"
        }
      ]
    }
  ]
}
