{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasm/0.3.0-dev.9facec7b2186/wasm-0.3.0-dev.9facec7b2186.module",
    "group": "uk.shusek.krwa",
    "module": "wasm",
    "version": "0.3.0-dev.9facec7b2186",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "wasm-iosArm64Main-0.3.0-dev.9facec7b2186.klib",
          "url": "wasm-iosarm64-0.3.0-dev.9facec7b2186.klib",
          "size": 370902,
          "sha512": "363afe68eeab482cef23d438d15e20dd4adf2a3f039f547b80b494189b924b363eb0f9a98a70889120627f20a37f16034525321d82398c95a780ca4458c1aee1",
          "sha256": "93aa19a95f43b2cb4cb52ee706b024b9402a7770f6ed228b2da6aa46cd7e05e2",
          "sha1": "1a605781f37ab2c23dc87ee704fce5d3e7a291d3",
          "md5": "f670f3edb6d726f5d76b86181d8ae590"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "wasm-iosarm64-0.3.0-dev.9facec7b2186-sources.jar",
          "url": "wasm-iosarm64-0.3.0-dev.9facec7b2186-sources.jar",
          "size": 82801,
          "sha512": "6dac747f4973b7f99bf5e885caddeccd39e8784e16efaac44ad138d7d04529e9fd7c8078b2d918a1daac8fc053fc577e3c06437ba549e70da0b32a84a50fd5ad",
          "sha256": "1def46b6feb1621c8659a2a272e42d2249d73032b81d2eb9fb341fdaf0c6a536",
          "sha1": "bae5901421489bdc1f99e2168fc3050e3b19a454",
          "md5": "9a6f81b8ab5973a09e97d73eab7dbe01"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "wasm-iosarm64-0.3.0-dev.9facec7b2186-metadata.jar",
          "url": "wasm-iosarm64-0.3.0-dev.9facec7b2186-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
