{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wasi-preview3/0.3.0-dev.a852e327fbb9/wasi-preview3-0.3.0-dev.a852e327fbb9.module",
    "group": "uk.shusek.krwa",
    "module": "wasi-preview3",
    "version": "0.3.0-dev.a852e327fbb9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-jvm-0.3.0-dev.a852e327fbb9.jar",
          "url": "wasi-preview3-jvm-0.3.0-dev.a852e327fbb9.jar",
          "size": 78656,
          "sha512": "2fc50833d95e6f36121a1d675d346848f8de603d7988e1040ed63920466d1ec717725940961f0adf86ad89601c40dad53ca6c1057be782209c628eb7ae3fa8b7",
          "sha256": "2f030d07d2fdf2485fcbddcd343f1d692a9675dfe2c43eecce967227675e1f58",
          "sha1": "2de3cc97e2fe7a416ad439932bb3759adfc795b7",
          "md5": "dddd57873c81ddc7e29f514cb1459be2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-preview3-jvm-0.3.0-dev.a852e327fbb9.jar",
          "url": "wasi-preview3-jvm-0.3.0-dev.a852e327fbb9.jar",
          "size": 78656,
          "sha512": "2fc50833d95e6f36121a1d675d346848f8de603d7988e1040ed63920466d1ec717725940961f0adf86ad89601c40dad53ca6c1057be782209c628eb7ae3fa8b7",
          "sha256": "2f030d07d2fdf2485fcbddcd343f1d692a9675dfe2c43eecce967227675e1f58",
          "sha1": "2de3cc97e2fe7a416ad439932bb3759adfc795b7",
          "md5": "dddd57873c81ddc7e29f514cb1459be2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "wasi-preview3-jvm-0.3.0-dev.a852e327fbb9-sources.jar",
          "url": "wasi-preview3-jvm-0.3.0-dev.a852e327fbb9-sources.jar",
          "size": 13083,
          "sha512": "31a62d268a78024942b990dcd3f91ddfd87a30dc62edc90cc53f772fa07a23be3d3327fcc690b9faca7515f4e1464a115dd2fb3a23d158f75fe8141523c1878a",
          "sha256": "ec20d5dde06db2c6b715c08b7efbe5b88f071e5ee4b45f046dfb253bbb4ff1bf",
          "sha1": "44b7bc4ac45baff1eb74d537cdc7c730205d0acf",
          "md5": "2feb72362ff7850f72656959c88ef185"
        }
      ]
    }
  ]
}
