{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "wasi",
    "version": "0.3.0-dev.59c0bdcaad2a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.59c0bdcaad2a"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "wasi-metadata-0.3.0-dev.59c0bdcaad2a.jar",
          "url": "wasi-0.3.0-dev.59c0bdcaad2a.jar",
          "size": 17386,
          "sha512": "aa1e399706c0f586cd6ea8c51afdfa72149aa0cf2387d6b966c9d0dd0bf9ad1ec11f9627646bb9d40dbce6ab1878e9d06fb3c45d176a9f236a1936643fccc2ee",
          "sha256": "47689046414de5de6ab2d0cf247df0efd56c53e48e38a87d9fbe31a85d6ed466",
          "sha1": "21664ef97b5b644e4c276dd0876597f1a6320bbf",
          "md5": "e296646f166f94e9f5e79e45a0f9b3de"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "wasi-kotlin-0.3.0-dev.59c0bdcaad2a-sources.jar",
          "url": "wasi-0.3.0-dev.59c0bdcaad2a-sources.jar",
          "size": 24795,
          "sha512": "ee63259063b516b6a4b8c79c7ac6e66f9e3848f2499cd7346911f3bb575d6c1bcb2b550ad6a2ca18773a9ed7753f23221c5aa79634e1350b0b0fff66e77cdeec",
          "sha256": "5e9ad56494bd8bc3e70fdf4d6877233bf703c01f349a7b49d1984143a6dd29fe",
          "sha1": "f8980b4fd1b4b8ab8dbaee40ff100db12a1e1fb0",
          "md5": "50e1cfc8c613d857f746f93ca5dff56e"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasi-iosarm64/0.3.0-dev.59c0bdcaad2a/wasi-iosarm64-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-iosarm64",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasi-iosarm64/0.3.0-dev.59c0bdcaad2a/wasi-iosarm64-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-iosarm64",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasi-iosarm64/0.3.0-dev.59c0bdcaad2a/wasi-iosarm64-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-iosarm64",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasi-iossimulatorarm64/0.3.0-dev.59c0bdcaad2a/wasi-iossimulatorarm64-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-iossimulatorarm64",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasi-iossimulatorarm64/0.3.0-dev.59c0bdcaad2a/wasi-iossimulatorarm64-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-iossimulatorarm64",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../wasi-iossimulatorarm64/0.3.0-dev.59c0bdcaad2a/wasi-iossimulatorarm64-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-iossimulatorarm64",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wasi-jvm/0.3.0-dev.59c0bdcaad2a/wasi-jvm-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-jvm",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wasi-jvm/0.3.0-dev.59c0bdcaad2a/wasi-jvm-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-jvm",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wasi-jvm/0.3.0-dev.59c0bdcaad2a/wasi-jvm-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-jvm",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wasi-wasm-js/0.3.0-dev.59c0bdcaad2a/wasi-wasm-js-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-wasm-js",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wasi-wasm-js/0.3.0-dev.59c0bdcaad2a/wasi-wasm-js-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-wasm-js",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wasi-wasm-js/0.3.0-dev.59c0bdcaad2a/wasi-wasm-js-0.3.0-dev.59c0bdcaad2a.module",
        "group": "uk.shusek.krwa",
        "module": "wasi-wasm-js",
        "version": "0.3.0-dev.59c0bdcaad2a"
      }
    }
  ]
}
