{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "component-model-tooling",
    "version": "0.3.0-dev.a852e327fbb9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-tooling-0.3.0-dev.a852e327fbb9.jar",
          "url": "component-model-tooling-0.3.0-dev.a852e327fbb9.jar",
          "size": 8462,
          "sha512": "165386febd278b69b72a80823f6a75d71f0af4ba8bfbac38946219114545e1056616a0ae92656687625e06b430fa1cd4d337dc4c3ae3674624bc162722a157d8",
          "sha256": "c48496e9d2bb9735e055f78f75115a22f634a9c5854937ee29855de9996fa203",
          "sha1": "ac8569d88892c3966264699319d6045dc2c9245a",
          "md5": "e35c22ca030630dd3397f26baa1e6711"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-bom",
          "version": {
            "requires": "9.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "log",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "runtime",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasi",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm-tools",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-dev.a852e327fbb9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "component-model-tooling-0.3.0-dev.a852e327fbb9.jar",
          "url": "component-model-tooling-0.3.0-dev.a852e327fbb9.jar",
          "size": 8462,
          "sha512": "165386febd278b69b72a80823f6a75d71f0af4ba8bfbac38946219114545e1056616a0ae92656687625e06b430fa1cd4d337dc4c3ae3674624bc162722a157d8",
          "sha256": "c48496e9d2bb9735e055f78f75115a22f634a9c5854937ee29855de9996fa203",
          "sha1": "ac8569d88892c3966264699319d6045dc2c9245a",
          "md5": "e35c22ca030630dd3397f26baa1e6711"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "component-model-tooling-0.3.0-dev.a852e327fbb9-sources.jar",
          "url": "component-model-tooling-0.3.0-dev.a852e327fbb9-sources.jar",
          "size": 3094,
          "sha512": "01f09333b8b290bafcc9fdfbccd37a76d75c8187c189087e71ab90b457f34636333d8dbda15d8a5371844c01cee72c3f5855053d75799ab9ff6fd7de8798732a",
          "sha256": "5178479ff9c54c6ea31b99d9d8e2031254c0c72bb9c1f8b39fea1691a345d910",
          "sha1": "33bdd0375929bea2d94786ea253206ec9bbac12e",
          "md5": "c064f93ed8d02cca6a61785c2cfb3a1e"
        }
      ]
    }
  ]
}
