name: Zig Testsuite

on:
  schedule:
   - cron: "0 0 * * *" # everyday

permissions:
  contents: read

jobs:
  fuzz:
    name: Zig Nightly Testsuite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Compile the Zig testsuite
        if: github.repository_owner == 'Shusek'
        run: ./scripts/build-zig-testsuite.sh
      - name: Nightly Test
        if: github.repository_owner == 'Shusek'
        run: ./gradlew --no-daemon :nightly-testsuite:test
