{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.shusek.krwa",
    "module": "codegen",
    "version": "0.3.0-dev.428bfc8e397e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-0.3.0-dev.428bfc8e397e.jar",
          "url": "codegen-0.3.0-dev.428bfc8e397e.jar",
          "size": 21881,
          "sha512": "d52d56816cb99cf42a784d401191f79a9a8aec5bfba1352e81ebf50b6e926385b35b1370b274d166640b588ab01a4f3bd43e15a4554f26de376d0e3200ec8920",
          "sha256": "d583c6fdea3e540c5a73ad336ac3d69f62c6fc9555ca1368103cfbf9b78cc357",
          "sha1": "f43d5bc175bb650c9dc70feaa0009ff5faaf6578",
          "md5": "ca0709c2658c3443336330173d42b59b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-bom",
          "version": {
            "requires": "9.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "annotations",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "wasm",
          "version": {
            "requires": "0.3.0-dev.428bfc8e397e"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-0.3.0-dev.428bfc8e397e.jar",
          "url": "codegen-0.3.0-dev.428bfc8e397e.jar",
          "size": 21881,
          "sha512": "d52d56816cb99cf42a784d401191f79a9a8aec5bfba1352e81ebf50b6e926385b35b1370b274d166640b588ab01a4f3bd43e15a4554f26de376d0e3200ec8920",
          "sha256": "d583c6fdea3e540c5a73ad336ac3d69f62c6fc9555ca1368103cfbf9b78cc357",
          "sha1": "f43d5bc175bb650c9dc70feaa0009ff5faaf6578",
          "md5": "ca0709c2658c3443336330173d42b59b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-0.3.0-dev.428bfc8e397e-sources.jar",
          "url": "codegen-0.3.0-dev.428bfc8e397e-sources.jar",
          "size": 5648,
          "sha512": "66677d0584a860cb064eb606c641fb99be38cee279aabe6f192e2c22bd5e5eea2897f283a63b7eac262ed733390b84b5592dcc1d721afcecb891a2d6f4854008",
          "sha256": "6609f6da7c328d6b3db2cb76ca1c9c28e83d6c5c848e9d95a81c275bff3520b4",
          "sha1": "148631fc8f85dcb2ce28e77769cc59748a290a0d",
          "md5": "65b67b04a9192d3edbc33ebb34a34342"
        }
      ]
    }
  ]
}
